# Generated by Django 5.2.2 on 2025-08-23 05:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен режим тех. работ')),
                ('title', models.CharField(default='Технические работы', max_length=200, verbose_name='Заголовок страницы тех. работ')),
                ('message', models.TextField(default='В настоящее время проводятся технические работы. Приносим извинения за неудобства.', verbose_name='Сообщение для пользователей')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время начала работ')),
                ('estimated_end_time', models.DateTimeField(blank=True, null=True, verbose_name='Ожидаемое время завершения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Режим технических работ',
                'verbose_name_plural': 'Режимы технических работ',
                'ordering': ['-created_at'],
            },
        ),
    ]
