import React, { useContext, useState } from 'react';
import { LanguageContext } from '../../contexts/LanguageContext';
import { Language } from '../../contexts/LanguageContextType';
import { useTheme } from '../../contexts/ThemeContext';
import HomeButton from '../shared/HomeButton';
import './BranchEmployees.scss';

type EmployeeData = {
  name: string;
  position: string;
  subjects: string;
  education: string;
  degree: string;
  title: string;
  qualification: string;
  retraining: string;
  experience: string;
  programs: string;
};

type ProgramData = {
  title: string;
  tableData: EmployeeData[];
};

type Translations = {
  [key in Language]: {
    programSelector: {
      label: string;
      programs: {
        [key: string]: ProgramData;
      };
    };
    tableHeaders: {
      name: string;
      position: string;
      subjects: string;
      education: string;
      degree: string;
      title: string;
      qualification: string;
      retraining: string;
      experience: string;
      programs: string;
    };
  };
};

const translations: Translations = {
  ru: {
    programSelector: {
      label: 'Выберите образовательную программу:',
      programs: {
        '7804': {
          title: 'Персональный состав педагогических работников образовательной программы «BM.7804.* Международное предпринимательство в цифровой экономике»',
          tableData: [
            { name: 'Алиев Магомед Далгатович', position: 'старший преподаватель', subjects: 'Учебная практика (научно-исследовательская работа)', education: 'Высшее образование, труд, учитель трудового обучения и общетехнических дисципли, научная специальность - Мировая экономика', degree: 'кандидат экономических наук', title: '', qualification: 'Повышение квалификации, Удостоверение 14/нип-09 от 2022-11-07, навыки инновационных подходов к преподаванию в высшей школе xxi века, 36 Часы', retraining: '', experience: '20', programs: '' },
            { name: 'Аренков Игорь Анатольевич', position: 'профессор', subjects: 'Поведение потребителей (онлайн-курс), Учебная практика (научно-исследовательская работа), Цифровая экономика: современные вызовы', education: 'Высшее образование, экономика и организация машиностроительной промышленн, инженер-экономист', degree: 'доктор экономических наук', title: 'профессор', qualification: 'Повышение квалификации, Удостоверение 005690 от 2021-12-06, использование цифровых компетенций в образовании, 32 Часы', retraining: '', experience: '35', programs: '' },
            { name: 'Беляева Олеся Александровна', position: 'доцент', subjects: 'Учебная практика (научно-исследовательская работа)', education: 'Высшее образование, менеджмент, менеджер', degree: 'кандидат экономических наук', title: 'доцент', qualification: 'Повышение квалификации, Удостоверение 170921 0000893 от 2021-11-30, использование электронной информационно-образовательной среды, 108 Часы', retraining: '', experience: '1', programs: '' },
            { name: 'Вейнер Ирина Николаевна', position: 'доцент', subjects: 'Статистические методы исследования рынка', education: 'Высшее образование, экономическая кибернетика, экономист-математик сельского хозяйства, научная специальность - Бухгалтерский учет, статистика', degree: 'кандидат экономических наук', title: '', qualification: 'Повышение квалификации, Удостоверение 772415095946 от 2022-03-29, 72 Часы', retraining: '', experience: '16', programs: '' },
            { name: 'Губина Марьяна Андреевна', position: 'доцент', subjects: 'Мировая экономика', education: 'Высшее образование, экономист, научная специальность - Мировая экономика', degree: 'кандидат экономических наук', title: '', qualification: 'Повышение квалификации, Сертификат OhesDV3mFF от 2024-02-27, школа руководителей образовательных программ, 1 Дни', retraining: '', experience: '21', programs: '' },
            { name: 'Дейнека Ольга Сергеевна', position: 'профессор', subjects: 'Университетская жизнь. Основы корпоративной этики (онлайн-курс)', education: 'Высшее образование, психология, психолог, научная специальность - Политическая психология', degree: 'доктор психологических наук', title: 'профессор', qualification: '', retraining: '', experience: '42', programs: '' },
            { name: 'Декалов Владислав Владимирович', position: 'доцент', subjects: 'Язык эффективной коммуникации (онлайн-курс)', education: 'Высшее образование, менеджмент 080200, магистр, научная специальность - Журналистика', degree: 'кандидат политических наук', title: '', qualification: 'Повышение квалификации, Удостоверение С-16128 от 2024-06-28, экспресс-курс: искусственный интеллект с нуля, 16 Часы', retraining: '', experience: '5', programs: '' },
            { name: 'Дмитрикова Екатерина Александровна', position: 'доцент', subjects: 'Основы противодействия коррупции и экстремизму (онлайн-курс)', education: 'Высшее образование, юриспруденция, юрист', degree: 'кандидат юридических наук', title: '', qualification: '', retraining: '', experience: '21', programs: '' },
            { name: 'Дорский Андрей Юрьевич', position: 'профессор', subjects: 'Язык эффективной коммуникации (онлайн-курс)', education: 'Высшее образование, история, учитель истории и обществоведения, Высшее образование, юриспруденция, магистр, научная специальность - Эстетика', degree: 'доктор философских наук', title: 'доцент', qualification: 'Повышение квалификации, Сертификат b3Y16hMDyx от 2024-02-27, школа руководителей образовательных программ, 1 Дни', retraining: 'Профессиональная переподготовка, Диплом 27 0014828 от 2020-09-14, реклама и связи с общественностью, 468 Часы', experience: '30', programs: '' },
            { name: 'Иванов Виктор Владимирович', position: 'профессор', subjects: 'Финансовый менеджмент', education: 'Высшее образование, экономическая кибернетика, экономист-математик, научная специальность - Экономика и управление народным хозяйством, научная специальность - Экономическая теория', degree: 'доктор экономических наук', title: 'профессор', qualification: 'Повышение квалификации, Удостоверение 190385789 от 2024-07-17, информационно-коммуникационные технологии в деятельности образовательной организации, 40 Часы', retraining: '', experience: '39', programs: '' },
            { name: 'Кадура Елена Вячеславовна', position: 'доцент', subjects: 'Практики оперативной аналитики', education: 'Высшее образование, математика, учитель математики и информатики, Высшее образование, педагогика, магистр педагогики, Высшее образование, прикладная математика и информатика, магистр, научная специальность - Психология труда, инженерная психология, эргономика', degree: 'кандидат психологических наук', title: '', qualification: 'Повышение квалификации, Удостоверение 190371111 от 2022-07-12, основы работы преподавателя в системе blackboard, 72 Часы', retraining: 'Профессиональная переподготовка, Диплом 272400239960 от 2014-06-06, преподаватель высшей школы', experience: '3', programs: '' },
            { name: 'Колычева Валерия Андреевна', position: 'доцент', subjects: 'Статистика с основами эконометрики', education: 'Высшее образование, экономическая теория, экономист, Высшее образование, история и теория изобразительного искусства, искусствовед, научная специальность - Бухгалтерский учет, статистика', degree: 'кандидат экономических наук', title: 'доцент', qualification: 'Повышение квалификации, Удостоверение 772418503533 от 2022-12-09, английский язык в профессиональной сфере (уровень с1), 72 Часы', retraining: '', experience: '15', programs: '' },
            { name: 'Кузьменко Александр Валентинович', position: 'доцент', subjects: 'Основы делового общения (онлайн-курс)', education: 'Высшее образование, автоматизированные системы управления, инженер-системотехник, Высшее образование, юриспруденция, юрист, научная специальность - Трудовое право; право социального обеспечения', degree: 'кандидат юридических наук', title: 'доцент по кафедре', qualification: '', retraining: '', experience: '28', programs: '' },
            { name: 'Львова Дина Алексеевна', position: 'профессор', subjects: 'Учет, отчетность и аудит в цифровой среде', education: 'Высшее образование, бухгалтерский учет и аудит, экономист, научная специальность - Бухгалтерский учет, статистика', degree: 'доктор экономических наук', title: 'доцент', qualification: 'Повышение квалификации, Сертификат 2022/237 от 2022-12-09, английский язык в профессиональной сфере (уровень в2), 72 Часы', retraining: '', experience: '21', programs: '' },
            { name: 'Лякин Александр Николаевич', position: 'профессор', subjects: 'Макроэкономика', education: 'Высшее образование, политическая экономия, экономист, преподаватель политической экономии, научная специальность - Экономическая теория', degree: 'доктор экономических наук', title: 'профессор', qualification: '', retraining: '', experience: '40', programs: '' },
            { name: 'Мелякова Евгения Валерьевна', position: 'доцент', subjects: 'Теория организации', education: 'Высшее образование, менеджмент в социальной сфере, экономист-менеджер туризма, научная специальность - Экономика и управление народным хозяйством', degree: 'кандидат экономических наук', title: 'доцент', qualification: 'Повышение квалификации, Удостоверение 5/нуп-1 от 2022-11-02, навыки управления проектами, 40 Часы', retraining: '', experience: '19', programs: '' },
            { name: 'Миланич Юлия Михайловна', position: 'доцент', subjects: 'Адаптация и обучение в Университете (ЭО)', education: 'Высшее образование, психология, психолог, преподаватель, научная специальность - Медицинская психология', degree: 'кандидат психологических наук', title: 'доцент по кафедре', qualification: 'Повышение квалификации, Удостоверение 781803095622 от 2021-12-17, организационные и психолого-педагогические основы инклюзивного высшего образования, 72 Часы', retraining: '', experience: '29', programs: '' },
            { name: 'Нестеров Игорь Олегович', position: 'доцент', subjects: 'Россия и Узбекистан в международных экономических отношениях', education: 'Высшее образование, мировая экономика, экономист-международник, научная специальность - Мировая экономика', degree: 'кандидат экономических наук', title: '', qualification: 'Повышение квалификации, Сертификат MIWVYcuOUO от 2024-02-27, школа руководителей образовательных программ, 1 Дни', retraining: '', experience: '22', programs: '' },
            { name: 'Салихова Яна Юрьевна', position: 'ДГПХ', subjects: 'Маркетинг', education: 'Высшее образование, маркетинг, экономист', degree: '', title: 'доцент', qualification: '', retraining: '', experience: '', programs: '' },
            { name: 'Слободянюк Вера Евгеньевна', position: 'старший преподаватель', subjects: 'Цифровая культура (ЭО)', education: 'Высшее образование, Инженер, Инженер по оптико-электронным приборам', degree: '', title: '', qualification: 'Повышение квалификации, Сертификат DEN53GBZUo от 2024-02-27, школа руководителей образовательных программ, 1 Дни', retraining: '', experience: '13', programs: '' },
            { name: 'Смирнов Артем Валентинович', position: 'доцент', subjects: 'Основы российской государственности', education: 'Высшее образование, политическая экономия, экономист, преподаватель политической экономии, Высшее образование, юрист, юриспруденция, научная специальность - Экономическая теория', degree: 'кандидат экономических наук', title: '', qualification: 'Повышение квалификации, Удостоверение 0000106041 от 2023-05-25, технология организации преподавания основ российской государственности, 72 Часы', retraining: '', experience: '31', programs: '' },
            { name: 'Ушанков Вячеслав Анатольевич', position: 'старший преподаватель', subjects: 'История экономических учений', education: 'Высшее образование, политическая экономия, экономист, преподаватель пол. экономии, научная специальность - Экономическая теория', degree: 'кандидат экономических наук', title: 'доцент', qualification: '', retraining: '', experience: '41', programs: '' },
            { name: 'Шеров-Игнатьев Владимир Генрихович', position: 'доцент', subjects: 'Страны Центральной Азии в мировой экономике, Страны и регионы в мировой экономике', education: 'Высшее образование, экономическая кибернетика, экономист-математик, научная специальность - Мировая экономика', degree: 'кандидат экономических наук', title: 'доцент', qualification: 'Повышение квалификации, Удостоверение ААА 180914709 от 2023-11-24, современная система международных экономических отношений, 16 Часы', retraining: '', experience: '40', programs: '' }
          ]
        },
        '7803': {
          title: 'Персональный состав педагогических работников образовательной программы «BM.7803.* Современный Китай: экономика, политика, общество (с изучением китайского языка)»',
          tableData: [
            { name: 'Байер Елена Михайловна', position: 'старший преподаватель', subjects: 'Право интеллектуальной собственности в цифровую эпоху (онлайн-курс)', education: 'Высшее образование, юриспруденция, юрист', degree: '', title: '', qualification: '', retraining: '', experience: '1', programs: '' },
            { name: 'Бочаров Виктор Владимирович', position: 'профессор', subjects: 'Концепции современного востоковедения, Политическая антропология', education: 'Высшее образование, востоковедение, африканистика, востоковед-филолог', degree: 'доктор исторических наук', title: '', qualification: '', retraining: '', experience: '27', programs: '' },
            { name: 'Дейнека Ольга Сергеевна', position: 'профессор', subjects: 'Университетская жизнь. Основы корпоративной этики (онлайн-курс)', education: 'Высшее образование, психология, психолог, научная специальность - Политическая психология', degree: 'доктор психологических наук', title: 'профессор', qualification: '', retraining: '', experience: '42', programs: '' },
            { name: 'Донская Александра Евгеньевна', position: 'доцент', subjects: 'Введение в китаеведение, Современные концепции новейшей истории и историографии Китая', education: 'Высшее образование, востоковедение, африканистика, востоковед-историк (история Китая), научная специальность - Всеобщая история (соответствующего периода)', degree: 'кандидат исторических наук', title: '', qualification: 'Повышение квалификации, Сертификат AzqsloGjOL от 2024-02-27, школа руководителей образовательных программ, 1 Дни', retraining: '', experience: '23', programs: '' },
            { name: 'Емельченкова Елена Николаевна', position: 'доцент', subjects: 'Концепции современного востоковедения', education: 'Высшее образование, юриспруденция, юрист, Высшее образование, востоковедение, африканистика, востоковед-филолог (китайская филология), научная специальность - Языки народов зарубежных стран Европы, Азии, Африки, аборигенов Америки и Австралии', degree: 'кандидат филологических наук', title: '', qualification: 'Повышение квалификации, Удостоверение 7827 00666274 от 2021-11-24, навыки решения конфликтных ситуаций, 32 Часы', retraining: '', experience: '14', programs: '' },
            { name: 'Емельянов Владимир Владимирович', position: 'профессор', subjects: 'Концепции современного востоковедения', education: 'Высшее образование, востоковедение, африканистика, востоковед-историк (ассириология), научная специальность - Историография, источниковедение и методы исторического исследования', degree: 'кандидат исторических наук, доктор философских наук', title: 'доцент', qualification: 'Повышение квалификации, Сертификат X8o3fqgOoe от 2024-02-27, школа руководителей образовательных программ, 1 Дни', retraining: '', experience: '32', programs: '' },
            { name: 'Желтов Александр Юрьевич', position: 'профессор', subjects: 'Концепции современного востоковедения', education: 'Высшее образование, востоковедение, африканистика, востоковед-филолог (языки банту), научная специальность - Языки народов зарубежных стран Европы, Азии, Африки, аборигенов Америки и Австралии', degree: 'доктор филологических наук', title: 'доцент', qualification: 'Повышение квалификации, Сертификат V9ou3WIbBM от 2024-02-27, школа руководителей образовательных программ, 1 Дни', retraining: '', experience: '31', programs: '' },
            { name: 'Колотов Владимир Николаевич', position: 'профессор', subjects: 'Концепции современного востоковедения', education: 'Высшее образование, востоковедение, африканистика, востоковед-филолог, востоковед-историк', degree: 'доктор исторических наук', title: 'доцент', qualification: 'Повышение квалификации, Сертификат lCowelgQXG от 2024-02-27, школа руководителей образовательных программ, 1 Дни', retraining: '', experience: '26', programs: '' },
            { name: 'Миланич Юлия Михайловна', position: 'доцент', subjects: 'Адаптация и обучение в Университете (ЭО)', education: 'Высшее образование, психология, психолог, преподаватель, научная специальность - Медицинская психология', degree: 'кандидат психологических наук', title: 'доцент по кафедре', qualification: 'Повышение квалификации, Удостоверение 781803095622 от 2021-12-17, организационные и психолого-педагогические основы инклюзивного высшего образования, 72 Часы', retraining: '', experience: '29', programs: '' },
            { name: 'Молдован Артём Анатольевич', position: 'доцент', subjects: 'Экономическое развитие современного Китая', education: 'Высшее образование, мировая экономика, экономист, научная специальность - Мировая экономика', degree: 'кандидат экономических наук', title: 'доцент', qualification: 'Повышение квалификации, Удостоверение 772418503660 от 2022-12-09, английский язык в профессиональной сфере (уровень в1), 72 Часы', retraining: '', experience: '14', programs: '' },
            { name: 'Османов Евгений Магомедович', position: 'доцент', subjects: 'Производственная практика. Научно-исследовательская работа', education: 'Высшее образование, востоковедение, африканистика (магистр), магистр востоковедения, африканистики, научная специальность - Всеобщая история (соответствующего периода)', degree: 'кандидат исторических наук', title: '', qualification: 'Повышение квалификации, Сертификат 9aM4Z2m7Ka от 2024-02-27, школа руководителей образовательных программ, 1 Дни', retraining: '', experience: '19', programs: '' },
            { name: 'Родионов Алексей Анатольевич', position: 'профессор', subjects: 'Информационные ресурсы и базы данных синологических исследований', education: 'Высшее образование, Филология, учитель китайского и английского языков, научная специальность - Литература народов стран зарубежья', degree: 'кандидат филологических наук', title: 'доцент', qualification: 'Повышение квалификации, Удостоверение ААА 180903996 от 2023-04-09, новый подходы и технологии в лингвистике для преподавателей перевода, 72 Часы', retraining: '', experience: '23', programs: '' },
            { name: 'Самойлов Николай Анатольевич', position: 'профессор', subjects: 'Внешняя политика Китая, Концепции современного востоковедения', education: 'Высшее образование, востоковедение, африканистика, востоковед-историк, научная специальность - Всеобщая история (соответствующего периода)', degree: 'доктор исторических наук', title: 'доцент', qualification: 'Повышение квалификации, Удостоверение 780500296785 от 2022-11-11, навыки решения конфликтных ситуаций, 40 Часы', retraining: '', experience: '44', programs: '' },
            { name: 'Слободянюк Вера Евгеньевна', position: 'старший преподаватель', subjects: 'Цифровая культура: технологии и безопасность (ЭО)', education: 'Высшее образование, Инженер, Инженер по оптико-электронным приборам', degree: '', title: '', qualification: 'Повышение квалификации, Сертификат DEN53GBZUo от 2024-02-27, школа руководителей образовательных программ, 1 Дни', retraining: '', experience: '13', programs: '' },
            { name: 'Старовойтова Елена Олеговна', position: 'доцент', subjects: 'Законодательство и правовое развитие современного Китая, Социально-политическая система и экономика Китая', education: 'Высшее образование, востоковедение, африканистика (магистр), магистр востоковедения, африканистики', degree: 'кандидат исторических наук', title: '', qualification: 'Повышение квалификации, Удостоверение 19 0373092 от 2022-11-30, педагогика и психология высшей школы и дополнительного профессионального образования, 72 Часы', retraining: '', experience: '12', programs: '' },
            { name: 'Сторожук Александр Георгиевич', position: 'профессор', subjects: 'Концепции современного востоковедения', education: 'Высшее образование, востоковедение, африканистика, востоковед-филолог (китайская филология), научная специальность - Литература народов стран зарубежья', degree: 'доктор филологических наук', title: 'профессор', qualification: 'Повышение квалификации, Сертификат CT3I0ucsPS от 2024-02-27, школа руководителей образовательных программ, 1 Дни', retraining: '', experience: '27', programs: '' }
          ]
        },
        '7801': {
          title: 'Персональный состав педагогических работников образовательной программы «BM.7801.* Международное частное право»',
          tableData: [
            { name: 'Архипов Владислав Владимирович', position: 'профессор', subjects: 'Информационные технологии в юриспруденции', education: 'Высшее образование, юриспруденция, юриспруденция, научная специальность - Теория и история права и государства', degree: 'доктор юридических наук', title: '', qualification: 'Повышение квалификации, Удостоверение 79280409 от 2024-09-30, общие вопросы охраны труда, 16 Часы', retraining: '', experience: '14', programs: '' },
            { name: 'Воронкова Светлана Аркадьевна', position: 'заместитель заведующего отделом', subjects: 'Информационные ресурсы для образовательной и научной деятельности', education: 'Высшее образование, Библиотековедение и библиография, библиотекарь-бибилиограф', degree: '', title: '', qualification: 'Повышение квалификации, Удостоверение 614/21 от 2021-11-30, администрирование саб ирбис64+, 72 Часы', retraining: '', experience: '', programs: '' },
            { name: 'Дейнека Ольга Сергеевна', position: 'профессор', subjects: 'Университетская жизнь. Основы корпоративной этики (онлайн-курс)', education: 'Высшее образование, психология, психолог, научная специальность - Политическая психология', degree: 'доктор психологических наук', title: 'профессор', qualification: '', retraining: '', experience: '42', programs: '' },
            { name: 'Игнатьев Александр Сергеевич', position: 'доцент', subjects: 'Право международных договоров России и Узбекистана, Право международных организаций, Проблемы международно-правового сближения национальных правовых систем', education: 'Высшее образование, юриспруденция, юрист', degree: 'кандидат юридических наук', title: '', qualification: 'Повышение квалификации, Удостоверение 0000131927 от 2023-08-24, методика преподавания основ российской государственности, 72 Часы', retraining: '', experience: '4', programs: '' },
            { name: 'Карандашов Иннокентий Игоревич', position: 'доцент', subjects: 'Курсовая работа, Наследование и семейные отношения в международном частном праве, Проблемы применения международного права в судебной и арбитражной практике в России и Узбекистане', education: 'Высшее образование, юриспруденция, юрист', degree: 'кандидат юридических наук', title: '', qualification: 'Повышение квалификации, Удостоверение 79280431 от 2024-09-30, общие вопросы охраны труда, 16 Часы', retraining: '', experience: '10', programs: '' },
            { name: 'Килинкарова Елена Васильевна', position: 'доцент', subjects: 'Международное налоговое право', education: 'Высшее образование, юриспруденция, юрист', degree: 'кандидат юридических наук', title: 'доцент', qualification: 'Повышение квалификации, Сертификат aak9rqqz5y от 2024-02-27, школа руководителей образовательных программ, 1 Дни', retraining: '', experience: '15', programs: '' },
            { name: 'Киселева Ольга Анатольевна', position: 'доцент', subjects: 'Международное публичное право', education: 'Высшее образование, юриспруденция, юрист, Высшее образование, актуальные проблемы преподавания и изучения церковно-, актуальные проблемы преподавания и изучения церковно-', degree: 'кандидат юридических наук', title: '', qualification: 'Повышение квалификации, Удостоверение ААА 180893323 от 2022-10-15, актуальные вопросы международно-правовых исследований, 16 Часы', retraining: '', experience: '1', programs: '' },
            { name: 'Курочкина Екатерина Михайловна', position: 'ассистент', subjects: 'Правовое регулирование внешнеэкономической деятельности, Признание и приведение в исполнение иностранных судебных и арбитражных решений', education: 'Высшее образование, юриспруденция, бакалавр, Высшее образование, международное право, магистр, Высшее образование, юриспруденция, исследователь. преподаватель-исследователь', degree: 'кандидат юридических наук', title: '', qualification: 'Повышение квалификации, Удостоверение 0000156435 от 2023-11-14, методика преподавания основ российской государственности, 72 Часы', retraining: '', experience: '', programs: '' },
            { name: 'Марусин Игорь Станиславович', position: 'профессор', subjects: 'Право Европейского Союза', education: 'Высшее образование, правоведение, юрист, научная специальность - Международное право; Европейское право', degree: 'доктор юридических наук', title: 'доцент по кафедре', qualification: '', retraining: '', experience: '34', programs: '' },
            { name: 'Миланич Юлия Михайловна', position: 'доцент', subjects: 'Адаптация и обучение в Университете (ЭО)', education: 'Высшее образование, психология, психолог, преподаватель, научная специальность - Медицинская психология', degree: 'кандидат психологических наук', title: 'доцент по кафедре', qualification: 'Повышение квалификации, Удостоверение 781803095622 от 2021-12-17, организационные и психолого-педагогические основы инклюзивного высшего образования, 72 Часы', retraining: '', experience: '29', programs: '' },
            { name: 'Платонова Наталья Вячеславовна', position: 'старший преподаватель', subjects: 'Арбитражный процесс (практикум)', education: 'Высшее образование, Юриспруденция, магистр', degree: '', title: '', qualification: '', retraining: '', experience: '4', programs: '' },
            { name: 'Поляков Андрей Васильевич', position: 'профессор', subjects: 'Проблемы философии права', education: 'Высшее образование, правоведение, юрист', degree: 'доктор юридических наук', title: 'профессор', qualification: 'Повышение квалификации, Удостоверение 12/нсв-12 от 2022-11-18, навыки совладания с профессиональным выгоранием, 36 Часы', retraining: '', experience: '37', programs: '' },
            { name: 'Скворцов Олег Юрьевич', position: 'профессор', subjects: 'Проблемы учения об арбитраже', education: 'Высшее образование, правоведение, юрист', degree: 'доктор юридических наук', title: 'профессор', qualification: '', retraining: '', experience: '23', programs: '' },
            { name: 'Слободянюк Вера Евгеньевна', position: 'старший преподаватель', subjects: 'Цифровая культура: технологии и безопасность (ЭО)', education: 'Высшее образование, Инженер, Инженер по оптико-электронным приборам', degree: '', title: '', qualification: 'Повышение квалификации, Сертификат DEN53GBZUo от 2024-02-27, школа руководителей образовательных программ, 1 Дни', retraining: '', experience: '13', programs: '' },
            { name: 'Соколовская Елена', position: 'доцент', subjects: 'Финансовая грамотность (онлайн-курс)', education: 'Высшее образование, менеджмент внешнеэкономической деятельности, магистр по менеджменту внешнеэкономической деятельности, научная специальность - Финансы, денежное обращение и кредит', degree: 'кандидат экономических наук', title: 'старший научный сотрудник', qualification: 'Повышение квалификации, Удостоверение 772416459555 2021/245 от 2021-12-15, английский язык в профессиональной сфере (уровень а2), 72 Часы', retraining: '', experience: '8', programs: '' },
            { name: 'Суязов Вячеслав Валерьевич', position: 'доцент', subjects: 'Основы правоведения (онлайн-курс)', education: 'Высшее образование, юриспруденция, юрист', degree: 'кандидат юридических наук', title: '', qualification: 'Повышение квалификации, Сертификат DXsP2OrzXK от 2024-02-27, школа руководителей образовательных программ, 1 Дни', retraining: '', experience: '4', programs: '' },
            { name: 'Терешкова Валентина Владимировна', position: 'доцент', subjects: 'Право международной торговли, Современные проблемы международного частного права', education: 'Высшее образование, правоведение, юрист', degree: 'кандидат юридических наук', title: 'доцент по кафедре', qualification: '', retraining: '', experience: '', programs: '' },
            { name: 'Титов Виктор Олегович', position: 'доцент', subjects: 'Управление бизнесом (онлайн-курс)', education: 'Высшее образование, экономика и управление на предприятии, экономист-менеджер, научная специальность - Финансы, денежное обращение и кредит', degree: 'кандидат экономических наук', title: '', qualification: 'Повышение квалификации, Удостоверение 7827 00669084 от 2021-12-01, навыки управления персоналом, 32 Часы', retraining: '', experience: '12', programs: '' }
          ]
        },
        '7802': {
          title: 'Персональный состав педагогических работников образовательной программы «CB.7802.* Программирование и информационные технологии»',
          tableData: [
            { name: 'Дегтярев Александр Борисович', position: 'профессор', subjects: 'Основы алгоритмов', education: 'Высшее образование, гидроаэродинамика, инженер-исследователь механик, научная специальность - Математическое моделирование', degree: 'доктор технических наук', title: 'доцент по кафедре', qualification: 'Повышение квалификации, Удостоверение 217262 от 2022-03-23, базовые компетенции для реализации дисциплин в области искусственного интеллекта, 36 Часы', retraining: '', experience: '28', programs: '' },
            { name: 'Дейнека Ольга Сергеевна', position: 'профессор', subjects: 'Университетская жизнь. Основы корпоративной этики (онлайн-курс)', education: 'Высшее образование, психология, психолог, научная специальность - Политическая психология', degree: 'доктор психологических наук', title: 'профессор', qualification: '', retraining: '', experience: '42', programs: '' },
            { name: 'Киямов Жасур Уткирович', position: 'ассистент', subjects: 'Программирование в Linux, Современные методы программирования', education: 'Высшее образование, системный анализ, информатика и управление, исследователь. преподаватель-исследователь', degree: 'кандидат технических наук', title: '', qualification: 'Повышение квалификации, Удостоверение 190 381 206 от 2024-04-05, основы работы преподавателя в системе blackboard, 72 Часы', retraining: '', experience: '1', programs: '' },
            { name: 'Миланич Юлия Михайловна', position: 'доцент', subjects: 'Адаптация и обучение в Университете (ЭО)', education: 'Высшее образование, психология, психолог, преподаватель, научная специальность - Медицинская психология', degree: 'кандидат психологических наук', title: 'доцент по кафедре', qualification: 'Повышение квалификации, Удостоверение 781803095622 от 2021-12-17, организационные и психолого-педагогические основы инклюзивного высшего образования, 72 Часы', retraining: '', experience: '29', programs: '' },
            { name: 'Михеев Сергей Евгеньевич', position: 'доцент', subjects: 'Алгебра', education: 'Высшее образование, механика, механик, научная специальность - Дискретная математика и математическая кибернетика', degree: 'доктор физико-математических наук', title: 'доцент', qualification: '', retraining: '', experience: '51', programs: '' },
            { name: 'Смирнов Артем Валентинович', position: 'доцент', subjects: 'Основы российской государственности', education: 'Высшее образование, политическая экономия, экономист, преподаватель политической экономии, Высшее образование, юрист, юриспруденция, научная специальность - Экономическая теория', degree: 'кандидат экономических наук', title: '', qualification: 'Повышение квалификации, Удостоверение 0000106041 от 2023-05-25, технология организации преподавания основ российской государственности, 72 Часы', retraining: '', experience: '31', programs: '' }
          ]
        }
      }
    },
    tableHeaders: {
      name: 'Ф.И.О. преподавателя, реализующего программу', position: 'Должность преподавателя', subjects: 'Перечень преподаваемых дисциплин', education: 'Уровень образования, квалификация', degree: 'Учёная степень педагогического работника', title: 'Учёное звание педагогического работника', qualification: 'Сведения о повышении квалификации (за последние 3 года)', retraining: 'Сведения о профессиональной переподготовке (при наличии)', experience: 'Сведения о продолжительности опыта (лет) работы в профессиональной сфере', programs: 'Наименование образовательных программ'
    }
  },
  uz: {
    programSelector: {
      label: 'Ta\'lim dasturini tanlang:',
      programs: {
        '7804': {
          title: '«BM.7804.* Raqamli iqtisodiyotda xalqaro tadbirkorlik» ta\'lim dasturi pedagog xodimlarining shaxsiy tarkibi',
          tableData: [
            { name: 'Aliyev Magomed Dalgatovich', position: 'katta o‘qituvchi', subjects: 'O‘quv amaliyoti (ilmiy-tadqiqot ishi)', education: 'Oliy ma’lumot, mehnat, mehnat ta’limi va umumtexnik fanlar o‘qituvchisi, ilmiy mutaxassislik - Jahon iqtisodiyoti', degree: 'iqtisodiyot fanlari nomzodi', title: '', qualification: 'Malaka oshirish, 2022-11-07 yildagi 14/nip-09-sonli guvohnoma, XXI asr oliy ta’limida o‘qitishning innovatsion yondashuvlari, 36 soat', retraining: '', experience: '20', programs: '' },
            { name: 'Arenkov Igor Anatolyevich', position: 'professor', subjects: 'Iste’molchilar xulq-atvori (onlayn-kurs), O‘quv amaliyoti (ilmiy-tadqiqot ishi), Raqamli iqtisodiyot: zamonaviy chaqiriqlar', education: 'Oliy ma’lumot, mashinasozlik sanoati iqtisodiyoti va tashkil etilishi, muhandis-iqtisodchi', degree: 'iqtisodiyot fanlari doktori', title: 'professor', qualification: 'Malaka oshirish, 2021-12-06 yildagi 005690-sonli guvohnoma, ta’limda raqamli kompetensiyalardan foydalanish, 32 soat', retraining: '', experience: '35', programs: '' },
            { name: 'Belyayeva Olesya Aleksandrovna', position: 'dotsent', subjects: 'O‘quv amaliyoti (ilmiy-tadqiqot ishi)', education: 'Oliy ma’lumot, menejment, menejer', degree: 'iqtisodiyot fanlari nomzodi', title: 'dotsent', qualification: 'Malaka oshirish, 2021-11-30 yildagi 170921 0000893-sonli guvohnoma, elektron axborot-ta’lim muhitidan foydalanish, 108 soat', retraining: '', experience: '1', programs: '' },
            { name: 'Veyner Irina Nikolayevna', position: 'dotsent', subjects: 'Bozorni tadqiq qilishning statistik usullari', education: 'Oliy ma’lumot, iqtisodiy kibernetika, qishloq xo‘jaligi iqtisodchi-matematigi, ilmiy mutaxassislik - Buxgalteriya hisobi, statistika', degree: 'iqtisodiyot fanlari nomzodi', title: '', qualification: 'Malaka oshirish, 2022-03-29 yildagi 772415095946-sonli guvohnoma, 72 soat', retraining: '', experience: '16', programs: '' },
            { name: 'Gubina Maryana Andreyevna', position: 'dotsent', subjects: 'Jahon iqtisodiyoti', education: 'Oliy ma’lumot, iqtisodchi, ilmiy mutaxassislik - Jahon iqtisodiyoti', degree: 'iqtisodiyot fanlari nomzodi', title: '', qualification: 'Malaka oshirish, 2024-02-27 yildagi OhesDV3mFF-sonli sertifikat, ta’lim dasturlari rahbarlari maktabi, 1 kun', retraining: '', experience: '21', programs: '' },
            { name: 'Deyneka Olga Sergeyevna', position: 'professor', subjects: 'Universitet hayoti. Korporativ etika asoslari (onlayn-kurs)', education: 'Oliy ma’lumot, psixologiya, psixolog, ilmiy mutaxassislik - Siyosiy psixologiya', degree: 'psixologiya fanlari doktori', title: 'professor', qualification: '', retraining: '', experience: '42', programs: '' },
            { name: 'Dekalov Vladislav Vladimirovich', position: 'dotsent', subjects: 'Samarali muloqot tili (onlayn-kurs)', education: 'Oliy ma’lumot, menejment 080200, magistr, ilmiy mutaxassislik - Jurnalistika', degree: 'siyosiy fanlar nomzodi', title: '', qualification: 'Malaka oshirish, 2024-06-28 yildagi S-16128-sonli guvohnoma, ekspress-kurs: sun’iy intellekt noldan, 16 soat', retraining: '', experience: '5', programs: '' },
            { name: 'Dmitrikova Yekaterina Aleksandrovna', position: 'dotsent', subjects: 'Korrupsiyaga va ekstremizmga qarshi kurash asoslari (onlayn-kurs)', education: 'Oliy ma’lumot, yurisprudensiya, huquqshunos', degree: 'yuridik fanlar nomzodi', title: '', qualification: '', retraining: '', experience: '21', programs: '' },
            { name: 'Dorskiy Andrey Yuryevich', position: 'professor', subjects: 'Samarali muloqot tili (onlayn-kurs)', education: 'Oliy ma’lumot, tarix, tarix va jamiyatshunoslik o‘qituvchisi, Oliy ma’lumot, yurisprudensiya, magistr, ilmiy mutaxassislik - Estetika', degree: 'falsafa fanlari doktori', title: 'dotsent', qualification: 'Malaka oshirish, 2024-02-27 yildagi b3Y16hMDyx-sonli sertifikat, ta’lim dasturlari rahbarlari maktabi, 1 kun', retraining: 'Kasbiy qayta tayyorlash, 2020-09-14 yildagi 27 0014828-sonli diplom, reklama va jamoatchilik bilan aloqalar, 468 soat', experience: '30', programs: '' },
            { name: 'Ivanov Viktor Vladimirovich', position: 'professor', subjects: 'Moliyaviy menejment', education: 'Oliy ma’lumot, iqtisodiy kibernetika, iqtisodchi-matematik, ilmiy mutaxassislik - Xalq xo‘jaligini iqtisodiyoti va boshqaruvi, ilmiy mutaxassislik - Iqtisodiy nazariya', degree: 'iqtisodiyot fanlari doktori', title: 'professor', qualification: 'Malaka oshirish, 2024-07-17 yildagi 190385789-sonli guvohnoma, ta’lim tashkiloti faoliyatida axborot-kommunikatsiya texnologiyalari, 40 soat', retraining: '', experience: '39', programs: '' },
            { name: 'Kadura Yelena Vyacheslavovna', position: 'dotsent', subjects: 'Operativ tahlil amaliyotlari', education: 'Oliy ma’lumot, matematika, matematika va informatika o‘qituvchisi, Oliy ma’lumot, pedagogika, pedagogika magistri, Oliy ma’lumot, amaliy matematika va informatika, magistr, ilmiy mutaxassislik - Mehnat psixologiyasi, muhandislik psixologiyasi, ergonomika', degree: 'psixologiya fanlari nomzodi', title: '', qualification: 'Malaka oshirish, 2022-07-12 yildagi 190371111-sonli guvohnoma, blackboard tizimida o‘qituvchi ishining asoslari, 72 soat', retraining: 'Kasbiy qayta tayyorlash, 2014-06-06 yildagi 272400239960-sonli diplom, oliy maktab o‘qituvchisi', experience: '3', programs: '' },
            { name: 'Kolycheva Valeriya Andreyevna', position: 'dotsent', subjects: 'Ekonometrika asoslari bilan statistika', education: 'Oliy ma’lumot, iqtisodiy nazariya, iqtisodchi, Oliy ma’lumot, tasviriy san’at tarixi va nazariyasi, san’atshunos, ilmiy mutaxassislik - Buxgalteriya hisobi, statistika', degree: 'iqtisodiyot fanlari nomzodi', title: 'dotsent', qualification: 'Malaka oshirish, 2022-12-09 yildagi 772418503533-sonli guvohnoma, kasbiy sohada ingliz tili (s1 daraja), 72 soat', retraining: '', experience: '15', programs: '' },
            { name: 'Kuzmenko Aleksandr Valentinovich', position: 'dotsent', subjects: 'Ishbilarmonlik muloqoti asoslari (onlayn-kurs)', education: 'Oliy ma’lumot, avtomatlashtirilgan boshqaruv tizimlari, muhandis-tizim texnigi, Oliy ma’lumot, yurisprudensiya, huquqshunos, ilmiy mutaxassislik - Mehnat huquqi; ijtimoiy ta’minot huquqi', degree: 'yuridik fanlar nomzodi', title: 'kafedra dotsenti', qualification: '', retraining: '', experience: '28', programs: '' },
            { name: 'Lvova Dina Alekseyevna', position: 'professor', subjects: 'Raqamli muhitda hisob, hisobot va audit', education: 'Oliy ma’lumot, buxgalteriya hisobi va audit, iqtisodchi, ilmiy mutaxassislik - Buxgalteriya hisobi, statistika', degree: 'iqtisodiyot fanlari doktori', title: 'dotsent', qualification: 'Malaka oshirish, 2022-12-09 yildagi 2022/237-sonli sertifikat, kasbiy sohada ingliz tili (v2 daraja), 72 soat', retraining: '', experience: '21', programs: '' },
            { name: 'Lyakin Aleksandr Nikolayevich', position: 'professor', subjects: 'Makroiqtisodiyot', education: 'Oliy ma’lumot, siyosiy iqtisod, iqtisodchi, siyosiy iqtisod o‘qituvchisi, ilmiy mutaxassislik - Iqtisodiy nazariya', degree: 'iqtisodiyot fanlari doktori', title: 'professor', qualification: '', retraining: '', experience: '40', programs: '' },
            { name: 'Melyakova Yevgeniya Valeryevna', position: 'dotsent', subjects: 'Tashkilot nazariyasi', education: 'Oliy ma’lumot, ijtimoiy sohada menejment, turizm iqtisodchi-menejeri, ilmiy mutaxassislik - Xalq xo‘jaligini iqtisodiyoti va boshqaruvi', degree: 'iqtisodiyot fanlari nomzodi', title: 'dotsent', qualification: 'Malaka oshirish, 2022-11-02 yildagi 5/nup-1-sonli guvohnoma, loyihalarni boshqarish ko‘nikmalari, 40 soat', retraining: '', experience: '19', programs: '' },
            { name: 'Milanich Yuliya Mixaylovna', position: 'dotsent', subjects: 'Universitetda adaptatsiya va o‘qitish (EO)', education: 'Oliy ma’lumot, psixologiya, psixolog, o‘qituvchi, ilmiy mutaxassislik - Tibbiy psixologiya', degree: 'psixologiya fanlari nomzodi', title: 'kafedra dotsenti', qualification: 'Malaka oshirish, 2021-12-17 yildagi 781803095622-sonli guvohnoma, inklyuziv oliy ta’limning tashkiliy va psixologik-pedagogik asoslari, 72 soat', retraining: '', experience: '29', programs: '' },
            { name: 'Nesterov Igor Olegovich', position: 'dotsent', subjects: 'Rossiya va O‘zbekiston xalqaro iqtisodiy munosabatlarda', education: 'Oliy ma’lumot, jahon iqtisodiyoti, iqtisodchi-xalqaro munosabatlar bo‘yicha mutaxassis, ilmiy mutaxassislik - Jahon iqtisodiyoti', degree: 'iqtisodiyot fanlari nomzodi', title: '', qualification: 'Malaka oshirish, 2024-02-27 yildagi MIWVYcuOUO-sonli sertifikat, ta’lim dasturlari rahbarlari maktabi, 1 kun', retraining: '', experience: '22', programs: '' },
            { name: 'Salixova Yana Yuryevna', position: 'DGPH', subjects: 'Marketing', education: 'Oliy ma’lumot, marketing, iqtisodchi', degree: '', title: 'dotsent', qualification: '', retraining: '', experience: '', programs: '' },
            { name: 'Slobodyanyuk Vera Yevgenyevna', position: 'katta o‘qituvchi', subjects: 'Raqamli madaniyat (EO)', education: 'Oliy ma’lumot, muhandis, optik-elektron asboblar bo‘yicha muhandis', degree: '', title: '', qualification: 'Malaka oshirish, 2024-02-27 yildagi DEN53GBZUo-sonli sertifikat, ta’lim dasturlari rahbarlari maktabi, 1 kun', retraining: '', experience: '13', programs: '' },
            { name: 'Smirnov Artyom Valentinovich', position: 'dotsent', subjects: 'Rossiya davlatchiligi asoslari', education: 'Oliy ma’lumot, siyosiy iqtisod, iqtisodchi, siyosiy iqtisod o‘qituvchisi, Oliy ma’lumot, huquqshunos, yurisprudensiya, ilmiy mutaxassislik - Iqtisodiy nazariya', degree: 'iqtisodiyot fanlari nomzodi', title: '', qualification: 'Malaka oshirish, 2023-05-25 yildagi 0000106041-sonli guvohnoma, Rossiya davlatchiligi asoslarini o‘qitishni tashkil etish texnologiyasi, 72 soat', retraining: '', experience: '31', programs: '' },
            { name: 'Ushankov Vyacheslav Anatolyevich', position: 'katta o‘qituvchi', subjects: 'Iqtisodiy ta’limotlar tarixi', education: 'Oliy ma’lumot, siyosiy iqtisod, iqtisodchi, siyosiy iqtisod o‘qituvchisi, ilmiy mutaxassislik - Iqtisodiy nazariya', degree: 'iqtisodiyot fanlari nomzodi', title: 'dotsent', qualification: '', retraining: '', experience: '41', programs: '' },
            { name: 'Sherov-Ignatyev Vladimir Genrixovich', position: 'dotsent', subjects: 'Markaziy Osiyo mamlakatlari jahon iqtisodiyotida, Jahon iqtisodiyotidagi mamlakatlar va mintaqalar', education: 'Oliy ma’lumot, iqtisodiy kibernetika, iqtisodchi-matematik, ilmiy mutaxassislik - Jahon iqtisodiyoti', degree: 'iqtisodiyot fanlari nomzodi', title: 'dotsent', qualification: 'Malaka oshirish, 2023-11-24 yildagi ААА 180914709-sonli guvohnoma, zamonaviy xalqaro iqtisodiy munosabatlar tizimi, 16 soat', retraining: '', experience: '40', programs: '' }
          ]
        },
        '7803': {
          title: '«BM.7803.* Zamonaviy Xitoy: iqtisodiyot, siyosat, jamiyat (xitoy tilini o\'rganish bilan)» ta\'lim dasturi pedagog xodimlarining shaxsiy tarkibi',
          tableData: [
            { name: 'Bayer Yelena Mixaylovna', position: 'katta o‘qituvchi', subjects: 'Raqamli davrda intellektual mulk huquqi (onlayn-kurs)', education: 'Oliy ma’lumot, yurisprudensiya, huquqshunos', degree: '', title: '', qualification: '', retraining: '', experience: '1', programs: '' },
            { name: 'Bocharov Viktor Vladimirovich', position: 'professor', subjects: 'Zamonaviy sharqshunoslik konsepsiyalari, Siyosiy antropologiya', education: 'Oliy ma’lumot, sharqshunoslik, afrikanistika, sharqshunos-filolog', degree: 'tarix fanlari doktori', title: '', qualification: '', retraining: '', experience: '27', programs: '' },
            { name: 'Deyneka Olga Sergeyevna', position: 'professor', subjects: 'Universitet hayoti. Korporativ etika asoslari (onlayn-kurs)', education: 'Oliy ma’lumot, psixologiya, psixolog, ilmiy mutaxassislik - Siyosiy psixologiya', degree: 'psixologiya fanlari doktori', title: 'professor', qualification: '', retraining: '', experience: '42', programs: '' },
            { name: 'Donskaya Aleksandra Yevgenyevna', position: 'dotsent', subjects: 'Xitoyshunoslikka kirish, Xitoyning eng yangi tarixi va tarixshunosligining zamonaviy konsepsiyalari', education: 'Oliy ma’lumot, sharqshunoslik, afrikanistika, sharqshunos-tarixchi (Xitoy tarixi), ilmiy mutaxassislik - Umumiy tarix (tegishli davr)', degree: 'tarix fanlari nomzodi', title: '', qualification: 'Malaka oshirish, 2024-02-27 yildagi AzqsloGjOL-sonli sertifikat, ta’lim dasturlari rahbarlari maktabi, 1 kun', retraining: '', experience: '23', programs: '' },
            { name: 'Yemelchenkova Yelena Nikolayevna', position: 'dotsent', subjects: 'Zamonaviy sharqshunoslik konsepsiyalari', education: 'Oliy ma’lumot, yurisprudensiya, huquqshunos, Oliy ma’lumot, sharqshunoslik, afrikanistika, sharqshunos-filolog (xitoy filologiyasi), ilmiy mutaxassislik - Yevropa, Osiyo, Afrika, Amerika va Avstraliya aborigenlari tillari', degree: 'filologiya fanlari nomzodi', title: '', qualification: 'Malaka oshirish, 2021-11-24 yildagi 7827 00666274-sonli guvohnoma, nizoli vaziyatlarni hal qilish ko‘nikmalari, 32 soat', retraining: '', experience: '14', programs: '' },
            { name: 'Yemelyanov Vladimir Vladimirovich', position: 'professor', subjects: 'Zamonaviy sharqshunoslik konsepsiyalari', education: 'Oliy ma’lumot, sharqshunoslik, afrikanistika, sharqshunos-tarixchi (ossuriyashunoslik), ilmiy mutaxassislik - Tarixshunoslik, manbashunoslik va tarixiy tadqiqot usullari', degree: 'tarix fanlari nomzodi, falsafa fanlari doktori', title: 'dotsent', qualification: 'Malaka oshirish, 2024-02-27 yildagi X8o3fqgOoe-sonli sertifikat, ta’lim dasturlari rahbarlari maktabi, 1 kun', retraining: '', experience: '32', programs: '' },
            { name: 'Jeltov Aleksandr Yuryevich', position: 'professor', subjects: 'Zamonaviy sharqshunoslik konsepsiyalari', education: 'Oliy ma’lumot, sharqshunoslik, afrikanistika, sharqshunos-filolog (bantu tillari), ilmiy mutaxassislik - Yevropa, Osiyo, Afrika, Amerika va Avstraliya aborigenlari tillari', degree: 'filologiya fanlari doktori', title: 'dotsent', qualification: 'Malaka oshirish, 2024-02-27 yildagi V9ou3WIbBM-sonli sertifikat, ta’lim dasturlari rahbarlari maktabi, 1 kun', retraining: '', experience: '31', programs: '' },
            { name: 'Kolotov Vladimir Nikolayevich', position: 'professor', subjects: 'Zamonaviy sharqshunoslik konsepsiyalari', education: 'Oliy ma’lumot, sharqshunoslik, afrikanistika, sharqshunos-filolog, sharqshunos-tarixchi', degree: 'tarix fanlari doktori', title: 'dotsent', qualification: 'Malaka oshirish, 2024-02-27 yildagi lCowelgQXG-sonli sertifikat, ta’lim dasturlari rahbarlari maktabi, 1 kun', retraining: '', experience: '26', programs: '' },
            { name: 'Milanich Yuliya Mixaylovna', position: 'dotsent', subjects: 'Universitetda adaptatsiya va o‘qitish (EO)', education: 'Oliy ma’lumot, psixologiya, psixolog, o‘qituvchi, ilmiy mutaxassislik - Tibbiy psixologiya', degree: 'psixologiya fanlari nomzodi', title: 'kafedra dotsenti', qualification: 'Malaka oshirish, 2021-12-17 yildagi 781803095622-sonli guvohnoma, inklyuziv oliy ta’limning tashkiliy va psixologik-pedagogik asoslari, 72 soat', retraining: '', experience: '29', programs: '' },
            { name: 'Moldovan Artyom Anatolyevich', position: 'dotsent', subjects: 'Zamonaviy Xitoyning iqtisodiy rivojlanishi', education: 'Oliy ma’lumot, jahon iqtisodiyoti, iqtisodchi, ilmiy mutaxassislik - Jahon iqtisodiyoti', degree: 'iqtisodiyot fanlari nomzodi', title: 'dotsent', qualification: 'Malaka oshirish, 2022-12-09 yildagi 772418503660-sonli guvohnoma, kasbiy sohada ingliz tili (b1 daraja), 72 soat', retraining: '', experience: '14', programs: '' },
            { name: 'Osmanov Yevgeniy Magomedovich', position: 'dotsent', subjects: 'Ishlab chiqarish amaliyoti. Ilmiy-tadqiqot ishi', education: 'Oliy ma’lumot, sharqshunoslik, afrikanistika (magistr), sharqshunoslik, afrikanistika magistri, ilmiy mutaxassislik - Umumiy tarix (tegishli davr)', degree: 'tarix fanlari nomzodi', title: '', qualification: 'Malaka oshirish, 2024-02-27 yildagi 9aM4Z2m7Ka-sonli sertifikat, ta’lim dasturlari rahbarlari maktabi, 1 kun', retraining: '', experience: '19', programs: '' },
            { name: 'Rodionov Aleksey Anatolyevich', position: 'professor', subjects: 'Sinologik tadqiqotlarning axborot resurslari va ma’lumotlar bazalari', education: 'Oliy ma’lumot, filologiya, xitoy va ingliz tillari o‘qituvchisi, ilmiy mutaxassislik - Chet el mamlakatlari adabiyoti', degree: 'filologiya fanlari nomzodi', title: 'dotsent', qualification: 'Malaka oshirish, 2023-04-09 yildagi ААА 180903996-sonli guvohnoma, tarjima o‘qituvchilari uchun lingvistikada yangi yondashuvlar va texnologiyalar, 72 soat', retraining: '', experience: '23', programs: '' },
            { name: 'Samoylov Nikolay Anatolyevich', position: 'professor', subjects: 'Xitoyning tashqi siyosati, Zamonaviy sharqshunoslik konsepsiyalari', education: 'Oliy ma’lumot, sharqshunoslik, afrikanistika, sharqshunos-tarixchi, ilmiy mutaxassislik - Umumiy tarix (tegishli davr)', degree: 'tarix fanlari doktori', title: 'dotsent', qualification: 'Malaka oshirish, 2022-11-11 yildagi 780500296785-sonli guvohnoma, nizoli vaziyatlarni hal qilish ko‘nikmalari, 40 soat', retraining: '', experience: '44', programs: '' },
            { name: 'Slobodyanyuk Vera Yevgenyevna', position: 'katta o‘qituvchi', subjects: 'Raqamli madaniyat: texnologiyalar va xavfsizlik (EO)', education: 'Oliy ma’lumot, muhandis, optik-elektron asboblar bo‘yicha muhandis', degree: '', title: '', qualification: 'Malaka oshirish, 2024-02-27 yildagi DEN53GBZUo-sonli sertifikat, ta’lim dasturlari rahbarlari maktabi, 1 kun', retraining: '', experience: '13', programs: '' },
            { name: 'Starovoytova Yelena Olegovna', position: 'dotsent', subjects: 'Zamonaviy Xitoyning qonunchiligi va huquqiy rivojlanishi, Xitoyning ijtimoiy-siyosiy tizimi va iqtisodiyoti', education: 'Oliy ma’lumot, sharqshunoslik, afrikanistika (magistr), sharqshunoslik, afrikanistika magistri', degree: 'tarix fanlari nomzodi', title: '', qualification: 'Malaka oshirish, 2022-11-30 yildagi 19 0373092-sonli guvohnoma, oliy maktab va qo‘shimcha kasbiy ta’lim pedagogikasi va psixologiyasi, 72 soat', retraining: '', experience: '12', programs: '' },
            { name: 'Storojuk Aleksandr Georgiyevich', position: 'professor', subjects: 'Zamonaviy sharqshunoslik konsepsiyalari', education: 'Oliy ma’lumot, sharqshunoslik, afrikanistika, sharqshunos-filolog (xitoy filologiyasi), ilmiy mutaxassislik - Chet el mamlakatlari adabiyoti', degree: 'filologiya fanlari doktori', title: 'professor', qualification: 'Malaka oshirish, 2024-02-27 yildagi CT3I0ucsPS-sonli sertifikat, ta’lim dasturlari rahbarlari maktabi, 1 kun', retraining: '', experience: '27', programs: '' }
          ]
        },
        '7801': {
          title: '«BM.7801.* Xalqaro xususiy huquq» ta\'lim dasturi pedagog xodimlarining shaxsiy tarkibi',
          tableData: [
            { name: 'Arxipov Vladislav Vladimirovich', position: 'professor', subjects: 'Yurisprudensiyada axborot texnologiyalari', education: 'Oliy ma’lumot, yurisprudensiya, yurisprudensiya, ilmiy mutaxassislik - Davlat va huquq nazariyasi va tarixi', degree: 'yuridik fanlar doktori', title: '', qualification: 'Malaka oshirish, 2024-09-30 yildagi 79280409-sonli guvohnoma, mehnatni muhofaza qilishning umumiy masalalari, 16 soat', retraining: '', experience: '14', programs: '' },
            { name: 'Voronkova Svetlana Arkadyevna', position: 'bo‘lim mudiri o‘rinbosari', subjects: 'Ta’lim va ilmiy faoliyat uchun axborot resurslari', education: 'Oliy ma’lumot, Kutubxonachilik va bibliografiya, kutubxonachi-bibliograf', degree: '', title: '', qualification: 'Malaka oshirish, 2021-11-30 yildagi 614/21-sonli guvohnoma, SAB IRBIS64+ administrirovkasi, 72 soat', retraining: '', experience: '', programs: '' },
            { name: 'Deyneka Olga Sergeyevna', position: 'professor', subjects: 'Universitet hayoti. Korporativ etika asoslari (onlayn-kurs)', education: 'Oliy ma’lumot, psixologiya, psixolog, ilmiy mutaxassislik - Siyosiy psixologiya', degree: 'psixologiya fanlari doktori', title: 'professor', qualification: '', retraining: '', experience: '42', programs: '' },
            { name: 'Ignatyev Aleksandr Sergeyevich', position: 'dotsent', subjects: 'Rossiya va O‘zbekiston xalqaro shartnomalari huquqi, Xalqaro tashkilotlar huquqi, Milliy huquqiy tizimlarning xalqaro-huquqiy yaqinlashuvi muammolari', education: 'Oliy ma’lumot, yurisprudensiya, huquqshunos', degree: 'yuridik fanlar nomzodi', title: '', qualification: 'Malaka oshirish, 2023-08-24 yildagi 0000131927-sonli guvohnoma, Rossiya davlatchiligi asoslarini o‘qitish metodikasi, 72 soat', retraining: '', experience: '4', programs: '' },
            { name: 'Karandashov Innokentiy Igorevich', position: 'dotsent', subjects: 'Kurs ishi, Xalqaro xususiy huquqda meros va oilaviy munosabatlar, Rossiya va O‘zbekistonda sud va arbitraj amaliyotida xalqaro huquqni qo‘llash muammolari', education: 'Oliy ma’lumot, yurisprudensiya, huquqshunos', degree: 'yuridik fanlar nomzodi', title: '', qualification: 'Malaka oshirish, 2024-09-30 yildagi 79280431-sonli guvohnoma, mehnatni muhofaza qilishning umumiy masalalari, 16 soat', retraining: '', experience: '10', programs: '' },
            { name: 'Kilinkarova Yelena Vasilyevna', position: 'dotsent', subjects: 'Xalqaro soliq huquqi', education: 'Oliy ma’lumot, yurisprudensiya, huquqshunos', degree: 'yuridik fanlar nomzodi', title: 'dotsent', qualification: 'Malaka oshirish, 2024-02-27 yildagi aak9rqqz5y-sonli sertifikat, ta’lim dasturlari rahbarlari maktabi, 1 kun', retraining: '', experience: '15', programs: '' },
            { name: 'Kiseleva Olga Anatolyevna', position: 'dotsent', subjects: 'Xalqaro ommaviy huquq', education: 'Oliy ma’lumot, yurisprudensiya, huquqshunos, Oliy ma’lumot, cherkov huquqini o‘qitish va o‘rganishning dolzarb muammolari, cherkov huquqini o‘qitish va o‘rganishning dolzarb muammolari', degree: 'yuridik fanlar nomzodi', title: '', qualification: 'Malaka oshirish, 2022-10-15 yildagi ААА 180893323-sonli guvohnoma, xalqaro-huquqiy tadqiqotlarning dolzarb masalalari, 16 soat', retraining: '', experience: '1', programs: '' },
            { name: 'Kurochkina Yekaterina Mixaylovna', position: 'assistent', subjects: 'Tashqi iqtisodiy faoliyatni huquqiy tartibga solish, Chet el sud va arbitraj qarorlarini tan olish va ijro etish', education: 'Oliy ma’lumot, yurisprudensiya, bakalavr, Oliy ma’lumot, xalqaro huquq, magistr, Oliy ma’lumot, yurisprudensiya, tadqiqotchi. o‘qituvchi-tadqiqotchi', degree: 'yuridik fanlar nomzodi', title: '', qualification: 'Malaka oshirish, 2023-11-14 yildagi 0000156435-sonli guvohnoma, Rossiya davlatchiligi asoslarini o‘qitish metodikasi, 72 soat', retraining: '', experience: '', programs: '' },
            { name: 'Marusin Igor Stanislavovich', position: 'professor', subjects: 'Yevropa Ittifoqi huquqi', education: 'Oliy ma’lumot, huquqshunoslik, huquqshunos, ilmiy mutaxassislik - Xalqaro huquq; Yevropa huquqi', degree: 'yuridik fanlar doktori', title: 'kafedra dotsenti', qualification: '', retraining: '', experience: '34', programs: '' },
            { name: 'Milanich Yuliya Mixaylovna', position: 'dotsent', subjects: 'Universitetda adaptatsiya va o‘qitish (EO)', education: 'Oliy ma’lumot, psixologiya, psixolog, o‘qituvchi, ilmiy mutaxassislik - Tibbiy psixologiya', degree: 'psixologiya fanlari nomzodi', title: 'kafedra dotsenti', qualification: 'Malaka oshirish, 2021-12-17 yildagi 781803095622-sonli guvohnoma, inklyuziv oliy ta’limning tashkiliy va psixologik-pedagogik asoslari, 72 soat', retraining: '', experience: '29', programs: '' },
            { name: 'Platonova Natalya Vyacheslavovna', position: 'katta o‘qituvchi', subjects: 'Arbitraj jarayoni (praktikum)', education: 'Oliy ma’lumot, Yurisprudensiya, magistr', degree: '', title: '', qualification: '', retraining: '', experience: '4', programs: '' },
            { name: 'Polyakov Andrey Vasilyevich', position: 'professor', subjects: 'Huquq falsafasi muammolari', education: 'Oliy ma’lumot, huquqshunoslik, huquqshunos', degree: 'yuridik fanlar doktori', title: 'professor', qualification: 'Malaka oshirish, 2022-11-18 yildagi 12/nsv-12-sonli guvohnoma, kasbiy charchoqni yengish ko‘nikmalari, 36 soat', retraining: '', experience: '37', programs: '' },
            { name: 'Skvortsov Oleg Yuryevich', position: 'professor', subjects: 'Arbitraj haqidagi ta’limot muammolari', education: 'Oliy ma’lumot, huquqshunoslik, huquqshunos', degree: 'yuridik fanlar doktori', title: 'professor', qualification: '', retraining: '', experience: '23', programs: '' },
            { name: 'Slobodyanyuk Vera Yevgenyevna', position: 'katta o‘qituvchi', subjects: 'Raqamli madaniyat: texnologiyalar va xavfsizlik (EO)', education: 'Oliy ma’lumot, muhandis, optik-elektron asboblar bo‘yicha muhandis', degree: '', title: '', qualification: 'Malaka oshirish, 2024-02-27 yildagi DEN53GBZUo-sonli sertifikat, ta’lim dasturlari rahbarlari maktabi, 1 kun', retraining: '', experience: '13', programs: '' },
            { name: 'Sokolovskaya Yelena', position: 'dotsent', subjects: 'Moliyaviy savodxonlik (onlayn-kurs)', education: 'Oliy ma’lumot, tashqi iqtisodiy faoliyat menejmenti, tashqi iqtisodiy faoliyat menejmenti bo‘yicha magistr, ilmiy mutaxassislik - Moliya, pul muomalasi va kredit', degree: 'iqtisodiyot fanlari nomzodi', title: 'katta ilmiy xodim', qualification: 'Malaka oshirish, 2021-12-15 yildagi 772416459555 2021/245-sonli guvohnoma, kasbiy sohada ingliz tili (a2 daraja), 72 soat', retraining: '', experience: '8', programs: '' },
            { name: 'Suyazov Vyacheslav Valeryevich', position: 'dotsent', subjects: 'Huquqshunoslik asoslari (onlayn-kurs)', education: 'Oliy ma’lumot, yurisprudensiya, huquqshunos', degree: 'yuridik fanlar nomzodi', title: '', qualification: 'Malaka oshirish, 2024-02-27 yildagi DXsP2OrzXK-sonli sertifikat, ta’lim dasturlari rahbarlari maktabi, 1 kun', retraining: '', experience: '4', programs: '' },
            { name: 'Tereshkova Valentina Vladimirovna', position: 'dotsent', subjects: 'Xalqaro savdo huquqi, Xalqaro xususiy huquqning zamonaviy muammolari', education: 'Oliy ma’lumot, huquqshunoslik, huquqshunos', degree: 'yuridik fanlar nomzodi', title: 'kafedra dotsenti', qualification: '', retraining: '', experience: '', programs: '' },
            { name: 'Titov Viktor Olegovich', position: 'dotsent', subjects: 'Biznesni boshqarish (onlayn-kurs)', education: 'Oliy ma’lumot, korxona iqtisodiyoti va boshqaruvi, iqtisodchi-menejer, ilmiy mutaxassislik - Moliya, pul muomalasi va kredit', degree: 'iqtisodiyot fanlari nomzodi', title: '', qualification: 'Malaka oshirish, 2021-12-01 yildagi 7827 00669084-sonli guvohnoma, xodimlarni boshqarish ko‘nikmalari, 32 soat', retraining: '', experience: '12', programs: '' }
          ]
        },
        '7802': {
          title: '«CB.7802.* Dasturlash va axborot texnologiyalari» ta\'lim dasturi pedagog xodimlarining shaxsiy tarkibi',
          tableData: [
            { name: 'Degtyarev Aleksandr Borisovich', position: 'professor', subjects: 'Algoritmlar asoslari', education: 'Oliy ma’lumot, gidroaerodinamika, muhandis-tadqiqotchi mexanik, ilmiy mutaxassislik - Matematik modellashtirish', degree: 'texnika fanlari doktori', title: 'kafedra dotsenti', qualification: 'Malaka oshirish, 2022-03-23 yildagi 217262-sonli guvohnoma, sun’iy intellekt sohasidagi fanlarni amalga oshirish uchun asosiy kompetensiyalar, 36 soat', retraining: '', experience: '28', programs: '' },
            { name: 'Deyneka Olga Sergeyevna', position: 'professor', subjects: 'Universitet hayoti. Korporativ etika asoslari (onlayn-kurs)', education: 'Oliy ma’lumot, psixologiya, psixolog, ilmiy mutaxassislik - Siyosiy psixologiya', degree: 'psixologiya fanlari doktori', title: 'professor', qualification: '', retraining: '', experience: '42', programs: '' },
            { name: 'Kiyamov Jasur Utkirovich', position: 'assistent', subjects: 'Linuxda dasturlash, Zamonaviy dasturlash usullari', education: 'Oliy ma’lumot, tizimli tahlil, informatika va boshqaruv, tadqiqotchi. o‘qituvchi-tadqiqotchi', degree: 'texnika fanlari nomzodi', title: '', qualification: 'Malaka oshirish, 2024-04-05 yildagi 190 381 206-sonli guvohnoma, blackboard tizimida o‘qituvchi ishining asoslari, 72 soat', retraining: '', experience: '1', programs: '' },
            { name: 'Milanich Yuliya Mixaylovna', position: 'dotsent', subjects: 'Universitetda adaptatsiya va o‘qitish (EO)', education: 'Oliy ma’lumot, psixologiya, psixolog, o‘qituvchi, ilmiy mutaxassislik - Tibbiy psixologiya', degree: 'psixologiya fanlari nomzodi', title: 'kafedra dotsenti', qualification: 'Malaka oshirish, 2021-12-17 yildagi 781803095622-sonli guvohnoma, inklyuziv oliy ta’limning tashkiliy va psixologik-pedagogik asoslari, 72 soat', retraining: '', experience: '29', programs: '' },
            { name: 'Mixeyev Sergey Yevgenyevich', position: 'dotsent', subjects: 'Algebra', education: 'Oliy ma’lumot, mexanika, mexanik, ilmiy mutaxassislik - Diskret matematika va matematik kibernetika', degree: 'fizika-matematika fanlari doktori', title: 'dotsent', qualification: '', retraining: '', experience: '51', programs: '' },
            { name: 'Smirnov Artyom Valentinovich', position: 'dotsent', subjects: 'Rossiya davlatchiligi asoslari', education: 'Oliy ma’lumot, siyosiy iqtisod, iqtisodchi, siyosiy iqtisod o‘qituvchisi, Oliy ma’lumot, huquqshunos, yurisprudensiya, ilmiy mutaxassislik - Iqtisodiy nazariya', degree: 'iqtisodiyot fanlari nomzodi', title: '', qualification: 'Malaka oshirish, 2023-05-25 yildagi 0000106041-sonli guvohnoma, Rossiya davlatchiligi asoslarini o‘qitishni tashkil etish texnologiyasi, 72 soat', retraining: '', experience: '31', programs: '' }
          ]
        }
      }
    },
    tableHeaders: {
      name: 'Dasturni amalga oshiruvchi o\'qituvchining F.I.Sh.', position: 'O\'qituvchining lavozimi', subjects: 'O\'qitiladigan fanlar ro\'yxati', education: 'Ta\'lim darajasi, malakasi', degree: 'Pedagog xodimning ilmiy darajasi', title: 'Pedagog xodimning ilmiy unvoni', qualification: 'Malaka oshirish haqida ma\'lumotlar (so\'nggi 3 yil)', retraining: 'Kasbiy qayta tayyorlash haqida ma\'lumotlar (agar mavjud bo\'lsa)', experience: 'Professional sohada ish tajribasi davomiyligi (yillar) haqida ma\'lumotlar', programs: 'Ta\'lim dasturlari nomi'
    }
  },
  en: {
    programSelector: {
      label: 'Select educational program:',
      programs: {
        '7804': {
          title: 'Personnel composition of teaching staff of the educational program «BM.7804.* International Entrepreneurship in Digital Economy»',
          tableData: [
            { name: 'Aliev Magomed Dalgatovich', position: 'Senior Lecturer', subjects: 'Educational practice (research work)', education: 'Higher education, labor, teacher of labor training and general technical disciplines, scientific specialty - World Economy', degree: 'Candidate of Economic Sciences', title: '', qualification: 'Professional development, Certificate 14/nip-09 from 2022-11-07, skills of innovative approaches to teaching in higher education in the 21st century, 36 Hours', retraining: '', experience: '20', programs: '' },
            { name: 'Arenkov Igor Anatolyevich', position: 'Professor', subjects: 'Consumer Behavior (online course), Educational practice (research work), Digital Economy: Modern Challenges', education: 'Higher education, economics and organization of the machine-building industry, engineer-economist', degree: 'Doctor of Economic Sciences', title: 'Professor', qualification: 'Professional development, Certificate 005690 from 2021-12-06, use of digital competencies in education, 32 Hours', retraining: '', experience: '35', programs: '' },
            { name: 'Belyaeva Olesya Aleksandrovna', position: 'Associate Professor', subjects: 'Educational practice (research work)', education: 'Higher education, management, manager', degree: 'Candidate of Economic Sciences', title: 'Associate Professor', qualification: 'Professional development, Certificate 170921 0000893 from 2021-11-30, use of electronic information and educational environment, 108 Hours', retraining: '', experience: '1', programs: '' },
            { name: 'Veyner Irina Nikolaevna', position: 'Associate Professor', subjects: 'Statistical Methods of Market Research', education: 'Higher education, economic cybernetics, economist-mathematician in agriculture, scientific specialty - Accounting, statistics', degree: 'Candidate of Economic Sciences', title: '', qualification: 'Professional development, Certificate 772415095946 from 2022-03-29, 72 Hours', retraining: '', experience: '16', programs: '' },
            { name: 'Gubina Maryana Andreevna', position: 'Associate Professor', subjects: 'World Economy', education: 'Higher education, economist, scientific specialty - World Economy', degree: 'Candidate of Economic Sciences', title: '', qualification: 'Professional development, Certificate OhesDV3mFF from 2024-02-27, school for heads of educational programs, 1 Day', retraining: '', experience: '21', programs: '' },
            { name: 'Deyneka Olga Sergeevna', position: 'Professor', subjects: 'University Life. Basics of Corporate Ethics (online course)', education: 'Higher education, psychology, psychologist, scientific specialty - Political Psychology', degree: 'Doctor of Psychological Sciences', title: 'Professor', qualification: '', retraining: '', experience: '42', programs: '' },
            { name: 'Dekalov Vladislav Vladimirovich', position: 'Associate Professor', subjects: 'Language of Effective Communication (online course)', education: 'Higher education, management 080200, master, scientific specialty - Journalism', degree: 'Candidate of Political Sciences', title: '', qualification: 'Professional development, Certificate S-16128 from 2024-06-28, express course: artificial intelligence from scratch, 16 Hours', retraining: '', experience: '5', programs: '' },
            { name: 'Dmitrikova Ekaterina Aleksandrovna', position: 'Associate Professor', subjects: 'Basics of Countering Corruption and Extremism (online course)', education: 'Higher education, jurisprudence, lawyer', degree: 'Candidate of Legal Sciences', title: '', qualification: '', retraining: '', experience: '21', programs: '' },
            { name: 'Dorsky Andrey Yuryevich', position: 'Professor', subjects: 'Language of Effective Communication (online course)', education: 'Higher education, history, teacher of history and social studies, Higher education, jurisprudence, master, scientific specialty - Aesthetics', degree: 'Doctor of Philosophical Sciences', title: 'Associate Professor', qualification: 'Professional development, Certificate b3Y16hMDyx from 2024-02-27, school for heads of educational programs, 1 Day', retraining: 'Professional retraining, Diploma 27 0014828 from 2020-09-14, advertising and public relations, 468 Hours', experience: '30', programs: '' },
            { name: 'Ivanov Viktor Vladimirovich', position: 'Professor', subjects: 'Financial Management', education: 'Higher education, economic cybernetics, economist-mathematician, scientific specialty - Economics and management of the national economy, scientific specialty - Economic theory', degree: 'Doctor of Economic Sciences', title: 'Professor', qualification: 'Professional development, Certificate 190385789 from 2024-07-17, information and communication technologies in the activities of an educational organization, 40 Hours', retraining: '', experience: '39', programs: '' },
            { name: 'Kadura Elena Vyacheslavovna', position: 'Associate Professor', subjects: 'Practices of Operational Analytics', education: 'Higher education, mathematics, teacher of mathematics and informatics, Higher education, pedagogy, master of pedagogy, Higher education, applied mathematics and informatics, master, scientific specialty - Labor psychology, engineering psychology, ergonomics', degree: 'Candidate of Psychological Sciences', title: '', qualification: 'Professional development, Certificate 190371111 from 2022-07-12, basics of a teacher\'s work in the blackboard system, 72 Hours', retraining: 'Professional retraining, Diploma 272400239960 from 2014-06-06, teacher of higher school', experience: '3', programs: '' },
            { name: 'Kolycheva Valeria Andreevna', position: 'Associate Professor', subjects: 'Statistics with the Basics of Econometrics', education: 'Higher education, economic theory, economist, Higher education, history and theory of fine arts, art historian, scientific specialty - Accounting, statistics', degree: 'Candidate of Economic Sciences', title: 'Associate Professor', qualification: 'Professional development, Certificate 772418503533 from 2022-12-09, English in the professional sphere (level C1), 72 Hours', retraining: '', experience: '15', programs: '' },
            { name: 'Kuzmenko Alexander Valentinovich', position: 'Associate Professor', subjects: 'Basics of Business Communication (online course)', education: 'Higher education, automated control systems, systems engineer, Higher education, jurisprudence, lawyer, scientific specialty - Labor law; social security law', degree: 'Candidate of Legal Sciences', title: 'Associate Professor of the department', qualification: '', retraining: '', experience: '28', programs: '' },
            { name: 'Lvova Dina Alekseevna', position: 'Professor', subjects: 'Accounting, Reporting and Auditing in the Digital Environment', education: 'Higher education, accounting and audit, economist, scientific specialty - Accounting, statistics', degree: 'Doctor of Economic Sciences', title: 'Associate Professor', qualification: 'Professional development, Certificate 2022/237 from 2022-12-09, English in the professional sphere (level B2), 72 Hours', retraining: '', experience: '21', programs: '' },
            { name: 'Lyakin Alexander Nikolaevich', position: 'Professor', subjects: 'Macroeconomics', education: 'Higher education, political economy, economist, teacher of political economy, scientific specialty - Economic theory', degree: 'Doctor of Economic Sciences', title: 'Professor', qualification: '', retraining: '', experience: '40', programs: '' },
            { name: 'Melyakova Evgenia Valerievna', position: 'Associate Professor', subjects: 'Organization Theory', education: 'Higher education, management in the social sphere, economist-manager of tourism, scientific specialty - Economics and management of the national economy', degree: 'Candidate of Economic Sciences', title: 'Associate Professor', qualification: 'Professional development, Certificate 5/nup-1 from 2022-11-02, project management skills, 40 Hours', retraining: '', experience: '19', programs: '' },
            { name: 'Milanich Yulia Mikhailovna', position: 'Associate Professor', subjects: 'Adaptation and Training at the University (EO)', education: 'Higher education, psychology, psychologist, teacher, scientific specialty - Medical psychology', degree: 'Candidate of Psychological Sciences', title: 'Associate Professor of the department', qualification: 'Professional development, Certificate 781803095622 from 2021-12-17, organizational and psychological-pedagogical foundations of inclusive higher education, 72 Hours', retraining: '', experience: '29', programs: '' },
            { name: 'Nesterov Igor Olegovich', position: 'Associate Professor', subjects: 'Russia and Uzbekistan in International Economic Relations', education: 'Higher education, world economy, international economist, scientific specialty - World Economy', degree: 'Candidate of Economic Sciences', title: '', qualification: 'Professional development, Certificate MIWVYcuOUO from 2024-02-27, school for heads of educational programs, 1 Day', retraining: '', experience: '22', programs: '' },
            { name: 'Salikhova Yana Yuryevna', position: 'Civil Law Contract', subjects: 'Marketing', education: 'Higher education, marketing, economist', degree: '', title: 'Associate Professor', qualification: '', retraining: '', experience: '', programs: '' },
            { name: 'Slobodyanyuk Vera Evgenievna', position: 'Senior Lecturer', subjects: 'Digital Culture (EO)', education: 'Higher education, Engineer, Engineer for optoelectronic devices', degree: '', title: '', qualification: 'Professional development, Certificate DEN53GBZUo from 2024-02-27, school for heads of educational programs, 1 Day', retraining: '', experience: '13', programs: '' },
            { name: 'Smirnov Artem Valentinovich', position: 'Associate Professor', subjects: 'Foundations of Russian Statehood', education: 'Higher education, political economy, economist, teacher of political economy, Higher education, lawyer, jurisprudence, scientific specialty - Economic theory', degree: 'Candidate of Economic Sciences', title: '', qualification: 'Professional development, Certificate 0000106041 from 2023-05-25, technology of organizing the teaching of the foundations of Russian statehood, 72 Hours', retraining: '', experience: '31', programs: '' },
            { name: 'Ushankov Vyacheslav Anatolyevich', position: 'Senior Lecturer', subjects: 'History of Economic Doctrines', education: 'Higher education, political economy, economist, teacher of political economy, scientific specialty - Economic theory', degree: 'Candidate of Economic Sciences', title: 'Associate Professor', qualification: '', retraining: '', experience: '41', programs: '' },
            { name: 'Sherov-Ignatiev Vladimir Genrikhovich', position: 'Associate Professor', subjects: 'Central Asian Countries in the World Economy, Countries and Regions in the World Economy', education: 'Higher education, economic cybernetics, economist-mathematician, scientific specialty - World Economy', degree: 'Candidate of Economic Sciences', title: 'Associate Professor', qualification: 'Professional development, Certificate AAA 180914709 from 2023-11-24, modern system of international economic relations, 16 Hours', retraining: '', experience: '40', programs: '' }
          ]
        },
        '7803': {
          title: 'Personnel composition of teaching staff of the educational program «BM.7803.* Contemporary China: Economy, Politics, Society (with Chinese Language Study)»',
          tableData: [
            { name: 'Bayer Elena Mikhailovna', position: 'Senior Lecturer', subjects: 'Intellectual Property Law in the Digital Age (online course)', education: 'Higher education, jurisprudence, lawyer', degree: '', title: '', qualification: '', retraining: '', experience: '1', programs: '' },
            { name: 'Bocharov Viktor Vladimirovich', position: 'Professor', subjects: 'Concepts of Modern Oriental Studies, Political Anthropology', education: 'Higher education, oriental studies, african studies, orientalist-philologist', degree: 'Doctor of Historical Sciences', title: '', qualification: '', retraining: '', experience: '27', programs: '' },
            { name: 'Deyneka Olga Sergeevna', position: 'Professor', subjects: 'University Life. Basics of Corporate Ethics (online course)', education: 'Higher education, psychology, psychologist, scientific specialty - Political Psychology', degree: 'Doctor of Psychological Sciences', title: 'Professor', qualification: '', retraining: '', experience: '42', programs: '' },
            { name: 'Donskaya Alexandra Evgenievna', position: 'Associate Professor', subjects: 'Introduction to Sinology, Modern Concepts of Modern History and Historiography of China', education: 'Higher education, oriental studies, african studies, orientalist-historian (history of China), scientific specialty - General History (corresponding period)', degree: 'Candidate of Historical Sciences', title: '', qualification: 'Professional development, Certificate AzqsloGjOL from 2024-02-27, school for heads of educational programs, 1 Day', retraining: '', experience: '23', programs: '' },
            { name: 'Emelchenkova Elena Nikolaevna', position: 'Associate Professor', subjects: 'Concepts of Modern Oriental Studies', education: 'Higher education, jurisprudence, lawyer, Higher education, oriental studies, african studies, orientalist-philologist (Chinese philology), scientific specialty - Languages of the peoples of foreign countries of Europe, Asia, Africa, aborigines of America and Australia', degree: 'Candidate of Philological Sciences', title: '', qualification: 'Professional development, Certificate 7827 00666274 from 2021-11-24, conflict resolution skills, 32 Hours', retraining: '', experience: '14', programs: '' },
            { name: 'Emelyanov Vladimir Vladimirovich', position: 'Professor', subjects: 'Concepts of Modern Oriental Studies', education: 'Higher education, oriental studies, african studies, orientalist-historian (assyriology), scientific specialty - Historiography, source studies and methods of historical research', degree: 'Candidate of Historical Sciences, Doctor of Philosophical Sciences', title: 'Associate Professor', qualification: 'Professional development, Certificate X8o3fqgOoe from 2024-02-27, school for heads of educational programs, 1 Day', retraining: '', experience: '32', programs: '' },
            { name: 'Zheltov Alexander Yuryevich', position: 'Professor', subjects: 'Concepts of Modern Oriental Studies', education: 'Higher education, oriental studies, african studies, orientalist-philologist (Bantu languages), scientific specialty - Languages of the peoples of foreign countries of Europe, Asia, Africa, aborigines of America and Australia', degree: 'Doctor of Philological Sciences', title: 'Associate Professor', qualification: 'Professional development, Certificate V9ou3WIbBM from 2024-02-27, school for heads of educational programs, 1 Day', retraining: '', experience: '31', programs: '' },
            { name: 'Kolotov Vladimir Nikolaevich', position: 'Professor', subjects: 'Concepts of Modern Oriental Studies', education: 'Higher education, oriental studies, african studies, orientalist-philologist, orientalist-historian', degree: 'Doctor of Historical Sciences', title: 'Associate Professor', qualification: 'Professional development, Certificate lCowelgQXG from 2024-02-27, school for heads of educational programs, 1 Day', retraining: '', experience: '26', programs: '' },
            { name: 'Milanich Yulia Mikhailovna', position: 'Associate Professor', subjects: 'Adaptation and Training at the University (EO)', education: 'Higher education, psychology, psychologist, teacher, scientific specialty - Medical psychology', degree: 'Candidate of Psychological Sciences', title: 'Associate Professor of the department', qualification: 'Professional development, Certificate 781803095622 from 2021-12-17, organizational and psychological-pedagogical foundations of inclusive higher education, 72 Hours', retraining: '', experience: '29', programs: '' },
            { name: 'Moldovan Artyom Anatolyevich', position: 'Associate Professor', subjects: 'Economic Development of Modern China', education: 'Higher education, world economy, economist, scientific specialty - World Economy', degree: 'Candidate of Economic Sciences', title: 'Associate Professor', qualification: 'Professional development, Certificate 772418503660 from 2022-12-09, English in the professional sphere (level B1), 72 Hours', retraining: '', experience: '14', programs: '' },
            { name: 'Osmanov Evgeny Magomedovich', position: 'Associate Professor', subjects: 'Production practice. Research work', education: 'Higher education, oriental studies, african studies (master), master of oriental studies, african studies, scientific specialty - General History (corresponding period)', degree: 'Candidate of Historical Sciences', title: '', qualification: 'Professional development, Certificate 9aM4Z2m7Ka from 2024-02-27, school for heads of educational programs, 1 Day', retraining: '', experience: '19', programs: '' },
            { name: 'Rodionov Alexey Anatolyevich', position: 'Professor', subjects: 'Information Resources and Databases of Sinological Research', education: 'Higher education, Philology, teacher of Chinese and English, scientific specialty - Literature of foreign countries', degree: 'Candidate of Philological Sciences', title: 'Associate Professor', qualification: 'Professional development, Certificate AAA 180903996 from 2023-04-09, new approaches and technologies in linguistics for translation teachers, 72 Hours', retraining: '', experience: '23', programs: '' },
            { name: 'Samoilov Nikolay Anatolyevich', position: 'Professor', subjects: 'Foreign Policy of China, Concepts of Modern Oriental Studies', education: 'Higher education, oriental studies, african studies, orientalist-historian, scientific specialty - General History (corresponding period)', degree: 'Doctor of Historical Sciences', title: 'Associate Professor', qualification: 'Professional development, Certificate 780500296785 from 2022-11-11, conflict resolution skills, 40 Hours', retraining: '', experience: '44', programs: '' },
            { name: 'Slobodyanyuk Vera Evgenievna', position: 'Senior Lecturer', subjects: 'Digital Culture: Technologies and Security (EO)', education: 'Higher education, Engineer, Engineer for optoelectronic devices', degree: '', title: '', qualification: 'Professional development, Certificate DEN53GBZUo from 2024-02-27, school for heads of educational programs, 1 Day', retraining: '', experience: '13', programs: '' },
            { name: 'Starovoytova Elena Olegovna', position: 'Associate Professor', subjects: 'Legislation and Legal Development of Modern China, Socio-political System and Economy of China', education: 'Higher education, oriental studies, african studies (master), master of oriental studies, african studies', degree: 'Candidate of Historical Sciences', title: '', qualification: 'Professional development, Certificate 19 0373092 from 2022-11-30, pedagogy and psychology of higher school and additional professional education, 72 Hours', retraining: '', experience: '12', programs: '' },
            { name: 'Storozhuk Alexander Georgievich', position: 'Professor', subjects: 'Concepts of Modern Oriental Studies', education: 'Higher education, oriental studies, african studies, orientalist-philologist (Chinese philology), scientific specialty - Literature of foreign countries', degree: 'Doctor of Philological Sciences', title: 'Professor', qualification: 'Professional development, Certificate CT3I0ucsPS from 2024-02-27, school for heads of educational programs, 1 Day', retraining: '', experience: '27', programs: '' }
          ]
        },
        '7801': {
          title: 'Personnel composition of teaching staff of the educational program «BM.7801.* International Private Law»',
          tableData: [
            { name: 'Arkhipov Vladislav Vladimirovich', position: 'Professor', subjects: 'Information Technologies in Jurisprudence', education: 'Higher education, jurisprudence, jurisprudence, scientific specialty - Theory and History of Law and State', degree: 'Doctor of Legal Sciences', title: '', qualification: 'Professional development, Certificate 79280409 from 2024-09-30, general issues of labor protection, 16 Hours', retraining: '', experience: '14', programs: '' },
            { name: 'Voronkova Svetlana Arkadievna', position: 'Deputy Head of Department', subjects: 'Information Resources for Educational and Scientific Activities', education: 'Higher education, Library Science and Bibliography, librarian-bibliographer', degree: '', title: '', qualification: 'Professional development, Certificate 614/21 from 2021-11-30, administration of SAB IRBIS64+, 72 Hours', retraining: '', experience: '', programs: '' },
            { name: 'Deyneka Olga Sergeevna', position: 'Professor', subjects: 'University Life. Basics of Corporate Ethics (online course)', education: 'Higher education, psychology, psychologist, scientific specialty - Political Psychology', degree: 'Doctor of Psychological Sciences', title: 'Professor', qualification: '', retraining: '', experience: '42', programs: '' },
            { name: 'Ignatiev Alexander Sergeevich', position: 'Associate Professor', subjects: 'Law of International Treaties of Russia and Uzbekistan, Law of International Organizations, Problems of International Legal Rapprochement of National Legal Systems', education: 'Higher education, jurisprudence, lawyer', degree: 'Candidate of Legal Sciences', title: '', qualification: 'Professional development, Certificate 0000131927 from 2023-08-24, methodology of teaching the foundations of Russian statehood, 72 Hours', retraining: '', experience: '4', programs: '' },
            { name: 'Karandashov Innokenty Igorevich', position: 'Associate Professor', subjects: 'Coursework, Inheritance and Family Relations in Private International Law, Problems of Applying International Law in Judicial and Arbitration Practice in Russia and Uzbekistan', education: 'Higher education, jurisprudence, lawyer', degree: 'Candidate of Legal Sciences', title: '', qualification: 'Professional development, Certificate 79280431 from 2024-09-30, general issues of labor protection, 16 Hours', retraining: '', experience: '10', programs: '' },
            { name: 'Kilinkarova Elena Vasilievna', position: 'Associate Professor', subjects: 'International Tax Law', education: 'Higher education, jurisprudence, lawyer', degree: 'Candidate of Legal Sciences', title: 'Associate Professor', qualification: 'Professional development, Certificate aak9rqqz5y from 2024-02-27, school for heads of educational programs, 1 Day', retraining: '', experience: '15', programs: '' },
            { name: 'Kiseleva Olga Anatolyevna', position: 'Associate Professor', subjects: 'Public International Law', education: 'Higher education, jurisprudence, lawyer, Higher education, current problems of teaching and studying church law, current problems of teaching and studying church law', degree: 'Candidate of Legal Sciences', title: '', qualification: 'Professional development, Certificate AAA 180893323 from 2022-10-15, current issues of international legal research, 16 Hours', retraining: '', experience: '1', programs: '' },
            { name: 'Kurochkina Ekaterina Mikhailovna', position: 'Assistant', subjects: 'Legal Regulation of Foreign Economic Activity, Recognition and Enforcement of Foreign Judicial and Arbitral Awards', education: 'Higher education, jurisprudence, bachelor, Higher education, international law, master, Higher education, jurisprudence, researcher. teacher-researcher', degree: 'Candidate of Legal Sciences', title: '', qualification: 'Professional development, Certificate 0000156435 from 2023-11-14, methodology of teaching the foundations of Russian statehood, 72 Hours', retraining: '', experience: '', programs: '' },
            { name: 'Marusin Igor Stanislavovich', position: 'Professor', subjects: 'Law of the European Union', education: 'Higher education, law, lawyer, scientific specialty - International law; European law', degree: 'Doctor of Legal Sciences', title: 'Associate Professor of the department', qualification: '', retraining: '', experience: '34', programs: '' },
            { name: 'Milanich Yulia Mikhailovna', position: 'Associate Professor', subjects: 'Adaptation and Training at the University (EO)', education: 'Higher education, psychology, psychologist, teacher, scientific specialty - Medical psychology', degree: 'Candidate of Psychological Sciences', title: 'Associate Professor of the department', qualification: 'Professional development, Certificate 781803095622 from 2021-12-17, organizational and psychological-pedagogical foundations of inclusive higher education, 72 Hours', retraining: '', experience: '29', programs: '' },
            { name: 'Platonova Natalya Vyacheslavovna', position: 'Senior Lecturer', subjects: 'Arbitration Process (practicum)', education: 'Higher education, Jurisprudence, master', degree: '', title: '', qualification: '', retraining: '', experience: '4', programs: '' },
            { name: 'Polyakov Andrey Vasilyevich', position: 'Professor', subjects: 'Problems of the Philosophy of Law', education: 'Higher education, law, lawyer', degree: 'Doctor of Legal Sciences', title: 'Professor', qualification: 'Professional development, Certificate 12/nsv-12 from 2022-11-18, skills for coping with professional burnout, 36 Hours', retraining: '', experience: '37', programs: '' },
            { name: 'Skvortsov Oleg Yuryevich', position: 'Professor', subjects: 'Problems of the Doctrine of Arbitration', education: 'Higher education, law, lawyer', degree: 'Doctor of Legal Sciences', title: 'Professor', qualification: '', retraining: '', experience: '23', programs: '' },
            { name: 'Slobodyanyuk Vera Evgenievna', position: 'Senior Lecturer', subjects: 'Digital Culture: Technologies and Security (EO)', education: 'Higher education, Engineer, Engineer for optoelectronic devices', degree: '', title: '', qualification: 'Professional development, Certificate DEN53GBZUo from 2024-02-27, school for heads of educational programs, 1 Day', retraining: '', experience: '13', programs: '' },
            { name: 'Sokolovskaya Elena', position: 'Associate Professor', subjects: 'Financial Literacy (online course)', education: 'Higher education, management of foreign economic activity, master of management of foreign economic activity, scientific specialty - Finance, money circulation and credit', degree: 'Candidate of Economic Sciences', title: 'Senior Researcher', qualification: 'Professional development, Certificate 772416459555 2021/245 from 2021-12-15, English in the professional sphere (level A2), 72 Hours', retraining: '', experience: '8', programs: '' },
            { name: 'Suyazov Vyacheslav Valerievich', position: 'Associate Professor', subjects: 'Basics of Law (online course)', education: 'Higher education, jurisprudence, lawyer', degree: 'Candidate of Legal Sciences', title: '', qualification: 'Professional development, Certificate DXsP2OrzXK from 2024-02-27, school for heads of educational programs, 1 Day', retraining: '', experience: '4', programs: '' },
            { name: 'Tereshkova Valentina Vladimirovna', position: 'Associate Professor', subjects: 'International Trade Law, Modern Problems of Private International Law', education: 'Higher education, law, lawyer', degree: 'Candidate of Legal Sciences', title: 'Associate Professor of the department', qualification: '', retraining: '', experience: '', programs: '' },
            { name: 'Titov Viktor Olegovich', position: 'Associate Professor', subjects: 'Business Management (online course)', education: 'Higher education, economics and management at the enterprise, economist-manager, scientific specialty - Finance, money circulation and credit', degree: 'Candidate of Economic Sciences', title: '', qualification: 'Professional development, Certificate 7827 00669084 from 2021-12-01, personnel management skills, 32 Hours', retraining: '', experience: '12', programs: '' }
          ]
        },
        '7802': {
          title: 'Personnel composition of teaching staff of the educational program «CB.7802.* Programming and Information Technologies»',
          tableData: [
            { name: 'Degtyarev Alexander Borisovich', position: 'Professor', subjects: 'Fundamentals of Algorithms', education: 'Higher education, hydroaerodynamics, research engineer in mechanics, scientific specialty - Mathematical Modeling', degree: 'Doctor of Technical Sciences', title: 'Associate Professor of the department', qualification: 'Professional development, Certificate 217262 from 2022-03-23, basic competencies for implementing disciplines in the field of artificial intelligence, 36 Hours', retraining: '', experience: '28', programs: '' },
            { name: 'Deyneka Olga Sergeevna', position: 'Professor', subjects: 'University Life. Basics of Corporate Ethics (online course)', education: 'Higher education, psychology, psychologist, scientific specialty - Political Psychology', degree: 'Doctor of Psychological Sciences', title: 'Professor', qualification: '', retraining: '', experience: '42', programs: '' },
            { name: 'Kiyamov Jasur Utkirovich', position: 'Assistant', subjects: 'Programming in Linux, Modern Programming Methods', education: 'Higher education, system analysis, informatics and management, researcher. teacher-researcher', degree: 'Candidate of Technical Sciences', title: '', qualification: 'Professional development, Certificate 190 381 206 from 2024-04-05, basics of a teacher\'s work in the blackboard system, 72 Hours', retraining: '', experience: '1', programs: '' },
            { name: 'Milanich Yulia Mikhailovna', position: 'Associate Professor', subjects: 'Adaptation and Training at the University (EO)', education: 'Higher education, psychology, psychologist, teacher, scientific specialty - Medical psychology', degree: 'Candidate of Psychological Sciences', title: 'Associate Professor of the department', qualification: 'Professional development, Certificate 781803095622 from 2021-12-17, organizational and psychological-pedagogical foundations of inclusive higher education, 72 Hours', retraining: '', experience: '29', programs: '' },
            { name: 'Mikheev Sergey Evgenievich', position: 'Associate Professor', subjects: 'Algebra', education: 'Higher education, mechanics, mechanic, scientific specialty - Discrete mathematics and mathematical cybernetics', degree: 'Doctor of Physical and Mathematical Sciences', title: 'Associate Professor', qualification: '', retraining: '', experience: '51', programs: '' },
            { name: 'Smirnov Artem Valentinovich', position: 'Associate Professor', subjects: 'Foundations of Russian Statehood', education: 'Higher education, political economy, economist, teacher of political economy, Higher education, lawyer, jurisprudence, scientific specialty - Economic theory', degree: 'Candidate of Economic Sciences', title: '', qualification: 'Professional development, Certificate 0000106041 from 2023-05-25, technology of organizing the teaching of the foundations of Russian statehood, 72 Hours', retraining: '', experience: '31', programs: '' }
          ]
        }
      }
    },
    tableHeaders: {
      name: 'Full name of the teacher implementing the program', position: 'Teacher position', subjects: 'List of taught disciplines', education: 'Education level, qualification', degree: 'Academic degree of the teaching staff', title: 'Academic title of the teaching staff', qualification: 'Information on professional development (last 3 years)', retraining: 'Information on professional retraining (if available)', experience: 'Information on the duration of experience (years) in the professional field', programs: 'Name of educational programs'
    }
  }
};

const BranchEmployees: React.FC = () => {
  const { theme } = useTheme();
  const langContext = useContext(LanguageContext);

  if (!langContext) {
    throw new Error('BranchEmployees must be used within a Language Provider');
  }

  const { language } = langContext;
  const t = translations[language];

  const [selectedProgram, setSelectedProgram] = useState<string>(Object.keys(t.programSelector.programs)[0]);

  const selectedProgramData = t.programSelector.programs[selectedProgram];

  return (
    <div className={`branch-employees ${theme}`}>
      <HomeButton />
      <div className="content-container">
        <div className="program-selector-container">
          <label htmlFor="program-select">{t.programSelector.label}</label>
          <select
            id="program-select"
            value={selectedProgram}
            onChange={(e) => setSelectedProgram(e.target.value)}
            className="program-select"
          >
            {Object.keys(t.programSelector.programs).map((programKey) => (
              <option key={programKey} value={programKey}>
                {t.programSelector.programs[programKey].title}
              </option>
            ))}
          </select>
        </div>

        <div className="header">
          <span className="header-icon">📋</span>
          <h1>{selectedProgramData.title}</h1>
        </div>
        
        <div className="table-container">
          <table className="employees-table">
            <thead>
              <tr>
                <th>{t.tableHeaders.name}</th>
                <th>{t.tableHeaders.position}</th>
                <th>{t.tableHeaders.subjects}</th>
                <th>{t.tableHeaders.education}</th>
                <th>{t.tableHeaders.degree}</th>
                <th>{t.tableHeaders.title}</th>
                <th>{t.tableHeaders.qualification}</th>
                <th>{t.tableHeaders.retraining}</th>
                <th>{t.tableHeaders.experience}</th>
                <th>{t.tableHeaders.programs}</th>
              </tr>
            </thead>
            <tbody>
              {selectedProgramData.tableData.map((employee, index) => (
                <tr key={index}>
                  <td>{employee.name}</td>
                  <td>{employee.position}</td>
                  <td>{employee.subjects}</td>
                  <td>{employee.education}</td>
                  <td>{employee.degree}</td>
                  <td>{employee.title}</td>
                  <td>{employee.qualification}</td>
                  <td>{employee.retraining}</td>
                  <td>{employee.experience}</td>
                  <td>{employee.programs}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default BranchEmployees;