# Generated by Django 5.2.5 on 2025-10-12 05:07

from django.db import migrations, models


def migrate_teacher_data(apps, schema_editor):
    """
    Custom migration to handle the teacher field change from ForeignKey to CharField.
    Since we're changing the field type, we'll just drop the old column and add a new one.
    """
    db_alias = schema_editor.connection.alias
    
    # Use raw SQL to drop the old teacher_id column and add new teacher column
    with schema_editor.connection.cursor() as cursor:
        # Drop the old foreign key column
        cursor.execute("""
            CREATE TABLE schedule_schedule_new (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                title varchar(200) NOT NULL,
                title_uz varchar(200) NOT NULL,
                title_en varchar(200) NOT NULL,
                day_of_week varchar(20) NOT NULL,
                start_time time NOT NULL,
                end_time time NOT NULL,
                is_visible bool NOT NULL,
                group_id bigint NOT NULL REFERENCES schedule_group(id),
                location_id bigint REFERENCES schedule_room(id),
                teacher varchar(200)
            );
        """)
        
        # Copy data from old table to new table (excluding teacher_id)
        cursor.execute("""
            INSERT INTO schedule_schedule_new 
                (id, title, title_uz, title_en, day_of_week, start_time, end_time, 
                 is_visible, group_id, location_id, teacher)
            SELECT 
                id, title, title_uz, title_en, day_of_week, start_time, end_time,
                is_visible, group_id, location_id, NULL
            FROM schedule_schedule;
        """)
        
        # Drop old table
        cursor.execute("DROP TABLE schedule_schedule;")
        
        # Rename new table to original name
        cursor.execute("ALTER TABLE schedule_schedule_new RENAME TO schedule_schedule;")


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(migrate_teacher_data, reverse_code=migrations.RunPython.noop),
    ]
