# Generated by Django 5.2.5 on 2025-10-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("superuser", "Superuser")],
                default="admin",
                max_length=20,
            ),
        ),
    ]
