# Generated by Django 5.2.7 on 2025-10-15 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                (
                    "title_uz",
                    models.CharField(
                        max_length=200, verbose_name="Заголовок на узбекском"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=200, verbose_name="Заголовок на английском"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "description_uz",
                    models.TextField(verbose_name="Описание на узбекском"),
                ),
                (
                    "description_en",
                    models.TextField(verbose_name="Описание на английском"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="announcements/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "publication_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата публикации"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="Видимость"),
                ),
            ],
            options={
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
            },
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Название"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Подпись"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="gallery/", verbose_name="Изображение"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="Видимость"),
                ),
                (
                    "announcement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="events.announcement",
                        verbose_name="Объявление",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="events.event",
                        verbose_name="Событие",
                    ),
                ),
                (
                    "news",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="events.news",
                        verbose_name="Новость",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение галереи",
                "verbose_name_plural": "Галерея",
            },
        ),
    ]
